/** Bass presets: sub, reese, acid, 808, FM, analog, fold, played basses. */
import { engine, knob, synth, type PresetSpec } from "../build.ts";

export const BASS: readonly PresetSpec[] = [
  {
    name: "sub-sine",
    category: "bass",
    tags: ["sub", "clean", "deep", "hiphop"],
    desc: "clean sine sub with a soft thump on every note",
    feature:
      "pitch envelope for the thump, soft drive for small-speaker harmonics",
    mono: true,
    layers: [
      synth("sine", {
        attack: 0.004,
        decay: 0.3,
        sustain: 1,
        release: 0.12,
        penv: 4,
        pattack: 0,
        pdecay: 0.05,
        psustain: 0,
        panchor: 0,
      }),
    ],
    fx: [
      ["distort", { type: "soft", drive: 0.6, mix: 0.5, tone: 3000 }],
      ["filter", { type: "lpf", cutoff: 900, resonance: 0.1 }],
    ],
    knobs: [
      knob(
        "Weight",
        [0, 1, 0.5],
        { "distort.mix": null },
        "blends in harmonics so the sub reads on small speakers",
      ),
      knob(
        "Thump",
        [0, 12, 4],
        { "synth.penv": null },
        "pitch drop at each note's start, in semitones",
      ),
      knob(
        "Drive",
        [0, 4, 0.6],
        { "distort.drive": null },
        "soft saturation amount",
      ),
      knob(
        "Release",
        [0.02, 1.5, 0.12],
        { "synth.release": null },
        "how long notes ring after release",
        "exp",
      ),
    ],
  },
  {
    name: "808-boom",
    category: "bass",
    tags: ["808", "trap", "hiphop", "sub", "drive"],
    desc: "long 808 sub with a pitch drop and a driven, gritty top",
    feature:
      "pitch envelope plus a sine-fold drive that grows with the Grit knob",
    mono: true,
    layers: [
      synth("sine", {
        attack: 0.002,
        decay: 1.6,
        sustain: 0.35,
        release: 0.5,
        penv: 12,
        pattack: 0,
        pdecay: 0.07,
        psustain: 0,
        panchor: 0,
      }),
    ],
    fx: [
      ["distort", { type: "sinefold", drive: 1.2, mix: 0.45, tone: 2500 }],
      [
        "compressor",
        { threshold: -18, ratio: 3, attack: 0.005, release: 0.2, makeup: 3 },
      ],
    ],
    knobs: [
      knob(
        "Boom",
        [0.3, 4, 1.6],
        { "synth.decay": null },
        "how long the 808 sustains",
        "exp",
      ),
      knob(
        "Punch",
        [0, 24, 12],
        { "synth.penv": null },
        "size of the pitch drop on the attack",
      ),
      knob(
        "Grit",
        [0, 1, 0.45],
        { "distort.mix": null },
        "blend of the folded, distorted top",
      ),
      knob(
        "Fold",
        [0, 4, 1.2],
        { "distort.drive": null },
        "how hard the wavefolder is driven",
      ),
    ],
  },
  {
    name: "reese",
    category: "bass",
    tags: ["dnb", "detuned", "unison", "dark", "wide"],
    desc: "seven detuned saws beating against each other under a moving low-pass",
    feature: "seven-voice unison detune with a slow synced filter LFO",
    mono: true,
    layers: [
      synth("supersaw", {
        unison: 7,
        detune: 0.18,
        spread: 0.35,
        attack: 0.01,
        sustain: 1,
        release: 0.15,
        lpf: 700,
        lpq: 2,
        ftype: "24db",
      }),
    ],
    fx: [
      ["distort", { type: "asym", drive: 1.2, mix: 0.4, tone: 5000 }],
      [
        "autofilter",
        {
          type: "lpf",
          cutoff: 900,
          resonance: 0.25,
          depth: 1,
          sync: 4,
          shape: "sine",
        },
      ],
      ["chorus", { rate: 0.3, depth: 0.25, mix: 0.2 }],
    ],
    knobs: [
      knob(
        "Width",
        [0, 0.6, 0.18],
        { "synth.detune": null },
        "detune between the seven saws, so the beating speed",
      ),
      knob(
        "Tone",
        [200, 3000, 700],
        { "synth.lpf": null },
        "low-pass cutoff",
        "exp",
      ),
      knob(
        "Motion",
        [0, 3, 1],
        { "autofilter.depth": null },
        "depth of the slow filter sweep, in octaves",
      ),
      knob("Grit", [0, 4, 1.2], { "distort.drive": null }, "asymmetric drive"),
    ],
  },
  {
    name: "acid-squelch",
    category: "bass",
    tags: ["acid", "303", "techno", "resonant", "glide"],
    desc: "303-style ladder squelch with accents and a dotted echo",
    feature:
      "ladder filter envelope with accent (faccent) and resonance near self-oscillation",
    mono: true,
    range: [36, 55],
    layers: [
      synth("sawtooth", {
        attack: 0.002,
        decay: 0.2,
        sustain: 0.5,
        release: 0.05,
        lpf: 380,
        lpq: 16,
        lpenv: 3.5,
        lpdecay: 0.18,
        lpsustain: 0,
        ftype: "ladder",
        faccent: 1.5,
      }),
    ],
    fx: [
      ["distort", { type: "diode", drive: 1, mix: 0.35, tone: 6000 }],
      ["filter", { type: "hpf", cutoff: 30, resonance: 0 }, "dcblock"],
      ["delay", { beats: 0.75, feedback: 0.3, mix: 0.12, highcut: 3000 }],
    ],
    knobs: [
      knob(
        "Cutoff",
        [100, 2000, 380],
        { "synth.lpf": null },
        "ladder cutoff",
        "exp",
      ),
      knob(
        "Squelch",
        [2, 28, 16],
        { "synth.lpq": null },
        "resonance, from round to screaming",
      ),
      knob(
        "Env",
        [0, 6, 3.5],
        { "synth.lpenv": null },
        "how far each note opens the filter, in octaves",
      ),
      knob(
        "Echo",
        [0, 0.5, 0.12],
        { "delay.mix": null },
        "dotted-eighth echo level",
      ),
    ],
  },
  {
    name: "fm-bass",
    category: "bass",
    tags: ["fm", "dx", "slap", "funk", "digital"],
    desc: "punchy two-operator FM bass whose bite decays with each note",
    feature:
      "FM index envelope: the modulator decays so the attack barks and the tail is round",
    mono: true,
    layers: [
      synth("sine", {
        attack: 0.002,
        decay: 0.5,
        sustain: 0.6,
        release: 0.08,
        fm: 3,
        fmh: 1,
        fmattack: 0,
        fmdecay: 0.18,
        fmsustain: 0.15,
        fmrelease: 0.1,
      }),
    ],
    fx: [["distort", { type: "soft", drive: 0.8, mix: 0.3, tone: 5000 }]],
    knobs: [
      knob(
        "Bite",
        [0, 10, 3],
        { "synth.fm": null },
        "FM index: brightness of the attack",
      ),
      knob(
        "Ratio",
        [0.5, 4, 1],
        { "synth.fmh": null },
        "modulator ratio: 1 hollow, 2 woody, 3 nasal",
      ),
      knob(
        "Decay",
        [0.03, 1, 0.18],
        { "synth.fmdecay": null },
        "how fast the bite fades",
        "exp",
      ),
      knob("Drive", [0, 3, 0.8], { "distort.drive": null }, "soft saturation"),
    ],
  },
  {
    name: "moog-bass",
    category: "bass",
    tags: ["analog", "mono", "funk", "warm", "glide"],
    desc: "warm 24 dB analog bass, two saws and a filter that snaps open",
    feature: "24 dB filter with its own envelope, two-voice unison and glide",
    mono: true,
    layers: [
      synth("sawtooth", {
        unison: 2,
        detune: 0.06,
        spread: 0,
        attack: 0.002,
        decay: 0.35,
        sustain: 0.7,
        release: 0.07,
        lpf: 350,
        lpq: 3,
        lpenv: 2.5,
        lpdecay: 0.22,
        lpsustain: 0.15,
        ftype: "24db",
      }),
    ],
    fx: [["distort", { type: "soft", drive: 0.7, mix: 0.4, tone: 4000 }]],
    knobs: [
      knob(
        "Tone",
        [100, 2000, 350],
        { "synth.lpf": null },
        "filter cutoff",
        "exp",
      ),
      knob(
        "Env",
        [0, 5, 2.5],
        { "synth.lpenv": null },
        "filter envelope amount, in octaves",
      ),
      knob(
        "Snap",
        [0.04, 0.8, 0.22],
        { "synth.lpdecay": null },
        "filter envelope decay",
        "exp",
      ),
      knob("Drive", [0, 3, 0.7], { "distort.drive": null }, "warm saturation"),
    ],
  },
  {
    name: "pluck-bass",
    category: "bass",
    tags: ["house", "pluck", "short", "square"],
    desc: "short square bass with a fast filter pluck for house and disco lines",
    feature: "pulse width and a fast filter envelope",
    mono: true,
    layers: [
      synth("pulse", {
        pw: 0.4,
        attack: 0.001,
        decay: 0.28,
        sustain: 0.05,
        release: 0.06,
        lpf: 300,
        lpq: 4,
        lpenv: 3.5,
        lpdecay: 0.1,
        lpsustain: 0,
        ftype: "24db",
      }),
    ],
    fx: [
      [
        "compressor",
        { threshold: -20, ratio: 3, attack: 0.003, release: 0.1, makeup: 3 },
      ],
    ],
    knobs: [
      knob(
        "Tone",
        [100, 1500, 300],
        { "synth.lpf": null },
        "filter cutoff",
        "exp",
      ),
      knob("Snap", [0, 6, 3.5], { "synth.lpenv": null }, "pluck amount"),
      knob(
        "Length",
        [0.08, 1, 0.28],
        { "synth.decay": null },
        "note length",
        "exp",
      ),
      knob(
        "Width",
        [0.1, 0.5, 0.4],
        { "synth.pw": null },
        "pulse width: thin to hollow",
      ),
    ],
  },
  {
    name: "fold-bass",
    category: "bass",
    tags: ["fold", "west-coast", "growl", "modern"],
    desc: "triangle wave pushed through a wavefolder for rich, growling overtones",
    feature:
      "wavefolding (distort type fold) swept by an envelope-following knob",
    mono: true,
    layers: [
      synth("triangle", {
        attack: 0.003,
        decay: 0.4,
        sustain: 0.8,
        release: 0.1,
        lpf: 1800,
        lpq: 1,
        ftype: "24db",
      }),
    ],
    fx: [
      [
        "distort",
        { type: "fold", drive: 2.5, mix: 0.7, tone: 5000, postgain: 0.7 },
      ],
      ["filter", { type: "lpf", cutoff: 2500, resonance: 0.15 }],
    ],
    knobs: [
      knob(
        "Fold",
        [0, 8, 2.5],
        { "distort.drive": null },
        "how many times the wave folds over",
      ),
      knob(
        "Tone",
        [300, 8000, 2500],
        { "filter.cutoff": null },
        "post-fold low-pass",
        "exp",
      ),
      knob(
        "Blend",
        [0, 1, 0.7],
        { "distort.mix": null },
        "clean triangle to fully folded",
      ),
      knob(
        "Body",
        [200, 6000, 1800],
        { "synth.lpf": null },
        "pre-fold cutoff: lower folds softer",
        "exp",
      ),
    ],
  },
  {
    name: "growl-bass",
    category: "bass",
    tags: ["dubstep", "vowel", "growl", "fm", "wobble"],
    desc: "FM saw that talks through a vowel filter swept by a synced LFO",
    feature: "FM saw source into a vowel formant morph driven by an LFO",
    mono: true,
    layers: [
      synth("sawtooth", {
        attack: 0.005,
        sustain: 1,
        release: 0.1,
        fm: 1.5,
        fmh: 0.5,
        lpf: 4000,
        lpq: 1,
      }),
    ],
    fx: [
      ["distort", { type: "hard", drive: 1.5, mix: 0.5, tone: 6000 }],
      ["vowel", { vowel: "o", to: "a", mix: 0.65, morph: 0.5 }],
      ["filter", { type: "lpf", cutoff: 5000, resonance: 0.1 }],
    ],
    mods: [
      {
        id: "lfo",
        type: "lfo",
        params: { shape: "sine", sync: 1 },
        to: "vowel.morph",
        amount: 0.5,
      },
    ],
    knobs: [
      knob(
        "Growl",
        [0, 6, 1.5],
        { "synth.fm": null },
        "FM index: snarl in the source",
      ),
      knob(
        "Vowel",
        [0, 1, 0.5],
        { "vowel.morph": null },
        "center of the o-to-a vowel sweep",
      ),
      knob(
        "Rate",
        [0.25, 4, 1],
        { "lfo.sync": null },
        "vowel LFO length in beats",
        "exp",
      ),
      knob("Drive", [0, 5, 1.5], { "distort.drive": null }, "hard clipping"),
    ],
  },
  {
    name: "upright-jazz",
    category: "bass",
    tags: ["acoustic", "jazz", "upright", "physical"],
    desc: "plucked upright bass with a woody body and thumb attack",
    feature: "physical string model: pluck position and body resonance",
    mono: true,
    layers: [
      engine(
        "string",
        "upright",
        {},
        { params: { pos: 0.2, bright: 0.45, ring: 2.5 } },
      ),
    ],
    fx: [
      [
        "compressor",
        { threshold: -22, ratio: 3, attack: 0.01, release: 0.2, makeup: 3 },
      ],
      ["reverb", { mix: 0.12, size: 0.3, fade: 1 }],
    ],
    knobs: [
      knob(
        "Thumb",
        [0.05, 0.5, 0.2],
        { "string.pos": null },
        "pluck position: near the bridge is brighter",
      ),
      knob(
        "Tone",
        [0, 1, 0.45],
        { "string.bright": null },
        "string brightness",
      ),
      knob(
        "Ring",
        [0.3, 8, 2.5],
        { "string.ring": null },
        "sustain time",
        "exp",
      ),
      knob("Room", [0, 0.5, 0.12], { "reverb.mix": null }, "room level"),
    ],
  },
  {
    name: "slap-bass",
    category: "bass",
    tags: ["funk", "slap", "electric", "physical"],
    range: [28, 45],
    guard: true,
    desc: "slapped electric bass with string buzz and a compressor",
    feature: "string fret buzz and pickup model, then compression",
    mono: true,
    layers: [
      engine("string", "slap", {}, { params: { buzz: 0.25, bright: 0.7 } }),
    ],
    fx: [
      ["filter", { type: "lpf", cutoff: 1600, resonance: 0.05 }],
      [
        "compressor",
        { threshold: -22, ratio: 2.5, attack: 0.004, release: 0.12, makeup: 6 },
      ],
    ],
    knobs: [
      knob(
        "Pop",
        [400, 6000, 1600],
        { "filter.cutoff": null },
        "how much of the slap's click comes through",
        "exp",
      ),
      knob("Buzz", [0, 1, 0.25], { "string.buzz": null }, "fret buzz"),
      knob(
        "Mute",
        [0, 1, 0],
        { "string.mute": null },
        "palm mute: shorter, thumpier notes",
      ),
      knob(
        "Punch",
        [-40, -6, -22],
        { "compressor.threshold": null },
        "compressor threshold: lower squeezes harder",
      ),
    ],
  },
  {
    name: "motown-bass",
    category: "bass",
    tags: ["electric", "soul", "flatwound", "muted"],
    range: [28, 48],
    guard: true,
    desc: "muted flatwound electric bass, round and short",
    feature: "string palm mute and damping",
    mono: true,
    layers: [
      engine("string", "motown", {}, { params: { mute: 0.35, damp: 0.55 } }),
    ],
    fx: [
      [
        "compressor",
        { threshold: -28, ratio: 4, attack: 0.003, release: 0.2, makeup: 18 },
      ],
    ],
    knobs: [
      knob("Mute", [0, 1, 0.35], { "string.mute": null }, "palm mute amount"),
      knob(
        "Dark",
        [0, 1, 0.55],
        { "string.damp": null },
        "string damping: higher is rounder",
      ),
      knob("Ring", [0.2, 6, 2], { "string.ring": null }, "sustain time", "exp"),
      knob(
        "Squash",
        [-40, -6, -28],
        { "compressor.threshold": null },
        "compression amount",
      ),
    ],
  },
];
