/** Keys presets: pianos, electric pianos, organs, clavs and synth keys. */
import { keys, knob, synth, type PresetSpec } from "../build.ts";

const room = (mix: number) =>
  ["reverb", { mix, size: 0.5, fade: 1.6, lowpass: 7000 }] as const;

export const KEYS: readonly PresetSpec[] = [
  {
    name: "concert-grand",
    category: "keys",
    tags: ["piano", "acoustic", "grand", "classical"],
    desc: "concert grand with hammer weight, string resonance and a hall",
    feature: "modeled piano: hammer hardness and touch response",
    layers: [keys("grand", "grand")],
    guard: true,
    fx: [
      [
        "compressor",
        { threshold: -30, ratio: 2.5, attack: 0.01, release: 0.25, makeup: 10 },
      ],
      ["reverb", { mix: 0.2, size: 0.7, fade: 2.2, lowpass: 8000 }],
    ],
    knobs: [
      knob(
        "Hammer",
        [0, 1, 0.5],
        { "keys.hardness": null },
        "hammer hardness: mellow to bright",
      ),
      knob(
        "Touch",
        [0, 1, 1],
        { "keys.touch": null },
        "how much velocity shapes tone",
      ),
      knob(
        "Sustain",
        [0.1, 4, 1],
        { "keys.decay": null },
        "string decay time scale",
        "exp",
      ),
      knob("Hall", [0, 0.6, 0.2], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "ballad-piano",
    category: "keys",
    tags: ["piano", "soft", "ballad", "pop"],
    desc: "soft ballad piano with a dark tone and a lush room",
    feature: "piano preset tuned soft, with felt and tone controls",
    layers: [keys("grand", "ballad")],
    guard: true,
    fx: [
      [
        "compressor",
        { threshold: -30, ratio: 2.5, attack: 0.01, release: 0.25, makeup: 10 },
      ],
      ["reverb", { mix: 0.25, size: 0.65, fade: 2.4, lowpass: 6500 }],
    ],
    knobs: [
      knob(
        "Felt",
        [0, 1, 0],
        { "keys.felt": null },
        "felt between hammer and string",
      ),
      knob("Hammer", [0, 1, 0.4], { "keys.hardness": null }, "hammer hardness"),
      knob(
        "Release",
        [0.1, 4, 1],
        { "keys.release": null },
        "damper release time",
        "exp",
      ),
      knob("Hall", [0, 0.6, 0.25], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "felt-piano",
    category: "keys",
    tags: ["piano", "felt", "intimate", "lofi", "ambient"],
    desc: "intimate felt piano, close-miked with mechanical noise",
    feature: "felt muting plus key and hammer noise",
    layers: [keys("felt", "felt")],
    guard: true,
    fx: [
      [
        "compressor",
        { threshold: -42, ratio: 4, attack: 0.008, release: 0.25, makeup: 20 },
      ],
      room(0.18),
    ],
    knobs: [
      knob(
        "Felt",
        [0, 1, 0.8],
        { "keys.felt": null },
        "how much felt softens the hammer",
      ),
      knob(
        "Noise",
        [0, 1, 0.25],
        { "keys.noise": null },
        "key and pedal noise",
      ),
      knob("Knock", [0, 1, 0.5], { "keys.knock": null }, "hammer knock"),
      knob("Room", [0, 0.6, 0.18], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "lofi-piano",
    category: "keys",
    tags: ["piano", "lofi", "tape", "chill", "wobble"],
    desc: "dusty upright through a wobbling tape and crushed bits",
    feature: "piano into tape wobble and a bitcrusher",
    layers: [keys("felt", "lofi")],
    guard: true,
    fx: [
      [
        "compressor",
        { threshold: -42, ratio: 4, attack: 0.008, release: 0.25, makeup: 20 },
      ],
      ["wobble", { depth: 25, rate: 0.6, drift: 0.4 }],
      ["crush", { bits: 10, coarse: 2, mix: 0.4 }],
      ["filter", { type: "lpf", cutoff: 4500 }],
      room(0.18),
    ],
    knobs: [
      knob(
        "Wobble",
        [0, 80, 25],
        { "wobble.depth": null },
        "tape pitch wobble (cents)",
      ),
      knob("Dust", [0, 1, 0.4], { "crush.mix": null }, "bitcrushed grit"),
      knob(
        "Tone",
        [1000, 9000, 4500],
        { "filter.cutoff": null },
        "darkness",
        "exp",
      ),
      knob("Room", [0, 0.6, 0.18], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "honky-tonk",
    category: "keys",
    tags: ["piano", "saloon", "detuned", "ragtime"],
    desc: "detuned saloon upright, bright and jangly",
    feature: "piano string detune between unison strings",
    layers: [keys("honkytonk", "honkytonk")],
    guard: true,
    fx: [
      [
        "compressor",
        { threshold: -30, ratio: 2.5, attack: 0.01, release: 0.25, makeup: 10 },
      ],
      room(0.15),
    ],
    knobs: [
      knob("Hammer", [0, 1, 0.6], { "keys.hardness": null }, "hammer hardness"),
      knob("Sustain", [0.1, 4, 1], { "keys.decay": null }, "decay", "exp"),
      knob("Knock", [0, 1, 0.5], { "keys.knock": null }, "hammer knock"),
      knob("Room", [0, 0.6, 0.15], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "prepared-piano",
    category: "keys",
    tags: ["piano", "prepared", "experimental", "cage"],
    desc: "Cage-style prepared piano: bolts and rubber on the strings",
    feature: "prepared piano string objects",
    layers: [keys("prepared", "prepared")],
    guard: true,
    fx: [
      [
        "compressor",
        { threshold: -30, ratio: 2.5, attack: 0.01, release: 0.25, makeup: 10 },
      ],
      room(0.2),
    ],
    knobs: [
      knob("Hammer", [0, 1, 0.5], { "keys.hardness": null }, "hammer hardness"),
      knob("Sustain", [0.1, 4, 1], { "keys.decay": null }, "decay", "exp"),
      knob(
        "Noise",
        [0, 1, 0.25],
        { "keys.noise": null },
        "rattle and key noise",
      ),
      knob("Room", [0, 0.6, 0.2], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "rhodes",
    category: "keys",
    tags: ["ep", "electric", "rhodes", "soul", "tremolo"],
    desc: "classic tine electric piano with stereo tremolo and chorus",
    feature: "tine model with bark on hard notes and stereo tremolo",
    layers: [keys("epiano", "suitcase")],
    guard: true,
    fx: [
      [
        "compressor",
        { threshold: -30, ratio: 2.5, attack: 0.01, release: 0.25, makeup: 10 },
      ],
      ["chorus", { rate: 0.6, depth: 0.25, mix: 0.2 }],
      room(0.15),
    ],
    knobs: [
      knob(
        "Bark",
        [0, 1, 0.15],
        { "keys.drive": null },
        "tine bark when played hard",
      ),
      knob(
        "Tremolo",
        [0, 1, 0.5],
        { "keys.trem": null },
        "stereo tremolo depth",
      ),
      knob(
        "Tone",
        [1000, 12000, 6000],
        { "keys.tone": null },
        "pickup tone",
        "exp",
      ),
      knob("Chorus", [0, 0.6, 0.2], { "chorus.mix": null }, "chorus"),
    ],
  },
  {
    name: "dx-ep",
    category: "keys",
    tags: ["ep", "fm", "dx7", "80s", "ballad"],
    desc: "DX7-style FM electric piano: a glassy tine over a warm body",
    feature: "two FM layers: a 14:1 tine click over a 1:1 body",
    layers: [
      synth(
        "sine",
        {
          attack: 0.002,
          decay: 1.6,
          sustain: 0.2,
          release: 0.5,
          fm: 1.2,
          fmh: 1,
          fmdecay: 1.2,
          fmsustain: 0.2,
        },
        { id: "body" },
      ),
      synth(
        "sine",
        {
          attack: 0.001,
          decay: 0.25,
          sustain: 0,
          release: 0.2,
          fm: 2.5,
          fmh: 14,
          fmdecay: 0.12,
          fmsustain: 0,
        },
        { id: "tine", gain: 0.3 },
      ),
    ],
    fx: [["chorus", { rate: 0.5, depth: 0.3, mix: 0.3 }], room(0.18)],
    knobs: [
      knob(
        "Tine",
        [0, 1, 0.3],
        { "tine.gain": null },
        "level of the glassy tine",
      ),
      knob("Warmth", [0, 4, 1.2], { "body.fm": null }, "FM index of the body"),
      knob("Decay", [0.3, 5, 1.6], { "body.decay": null }, "note decay", "exp"),
      knob("Chorus", [0, 0.7, 0.3], { "chorus.mix": null }, "chorus"),
    ],
  },
  {
    name: "wurli",
    category: "keys",
    tags: ["ep", "wurlitzer", "reed", "soul", "gritty"],
    desc: "reedy Wurlitzer that growls when you dig in",
    feature: "reed electric piano with drive and vibrato",
    layers: [keys("wurli", "wurli")],
    fx: [room(0.12)],
    knobs: [
      knob("Growl", [0, 1, 0.3], { "keys.drive": null }, "amp growl"),
      knob("Vibrato", [0, 1, 0], { "keys.trem": null }, "tremolo"),
      knob("Tone", [1000, 12000, 6000], { "keys.tone": null }, "tone", "exp"),
      knob("Room", [0, 0.5, 0.12], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "funk-clav",
    category: "keys",
    tags: ["clav", "funk", "wah", "percussive"],
    desc: "funky clavinet through an auto-wah",
    feature: "clav model into an envelope-following autofilter",
    layers: [keys("clav", "funkclav")],
    guard: true,
    fx: [
      [
        "compressor",
        { threshold: -30, ratio: 2.5, attack: 0.01, release: 0.25, makeup: 10 },
      ],
      [
        "autofilter",
        {
          type: "bpf",
          cutoff: 900,
          resonance: 0.5,
          depth: 1.5,
          follow: 3,
          sync: 0,
          rate: 0.01,
        },
      ],
      room(0.08),
    ],
    knobs: [
      knob(
        "Wah",
        [0, 6, 3],
        { "autofilter.follow": null },
        "how far your playing opens the wah",
      ),
      knob(
        "Center",
        [300, 3000, 900],
        { "autofilter.cutoff": null },
        "wah center",
        "exp",
      ),
      knob("Snap", [0, 1, 0.5], { "keys.hardness": null }, "string snap"),
      knob("Room", [0, 0.4, 0.08], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "rock-organ",
    category: "keys",
    tags: ["organ", "tonewheel", "b3", "leslie", "rock"],
    desc: "full drawbar tonewheel organ, overdriven through a spinning leslie",
    feature: "tonewheel drawbars, key click and the rotary speaker",
    layers: [keys("tonewheel", "tonewheel")],
    fx: [room(0.1)],
    knobs: [
      knob("Drive", [0, 1, 0.4], { "keys.drive": null }, "tube overdrive"),
      knob(
        "Rotor",
        [0, 2, 1],
        { "keys.rotary": null },
        "leslie: stop, slow, fast",
      ),
      knob("Click", [0, 1, 0.5], { "keys.knock": null }, "key click"),
      knob("Room", [0, 0.4, 0.1], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "gospel-organ",
    category: "keys",
    tags: ["organ", "gospel", "b3", "soul"],
    desc: "gospel drawbars with percussion and a fast leslie",
    feature: "drawbar registration with percussion",
    layers: [keys("tonewheel", "gospel")],
    fx: [room(0.15)],
    knobs: [
      knob("Drive", [0, 1, 0.25], { "keys.drive": null }, "overdrive"),
      knob("Rotor", [0, 2, 2], { "keys.rotary": null }, "leslie speed"),
      knob("Click", [0, 1, 0.5], { "keys.knock": null }, "key click"),
      knob("Room", [0, 0.5, 0.15], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "jazz-organ",
    category: "keys",
    tags: ["organ", "jazz", "b3", "mellow"],
    desc: "mellow jazz drawbars with a slow leslie",
    feature: "drawbar registration with a slow rotor",
    layers: [keys("tonewheel", "jazzorgan")],
    fx: [room(0.12)],
    knobs: [
      knob("Drive", [0, 1, 0.1], { "keys.drive": null }, "overdrive"),
      knob("Rotor", [0, 2, 1], { "keys.rotary": null }, "leslie speed"),
      knob("Click", [0, 1, 0.4], { "keys.knock": null }, "key click"),
      knob("Room", [0, 0.5, 0.12], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "combo-organ",
    category: "keys",
    tags: ["organ", "combo", "60s", "farfisa", "vox"],
    desc: "reedy 60s transistor combo organ with vibrato",
    feature: "transistor combo organ voices",
    layers: [keys("combo", "vox")],
    fx: [room(0.15)],
    knobs: [
      knob("Vibrato", [0, 1, 0.3], { "keys.vibe": null }, "vibrato"),
      knob("Drive", [0, 1, 0.2], { "keys.drive": null }, "amp drive"),
      knob("Tone", [1000, 12000, 6000], { "keys.tone": null }, "tone", "exp"),
      knob("Room", [0, 0.5, 0.15], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "church-organ",
    category: "keys",
    tags: ["organ", "pipe", "church", "cathedral"],
    desc: "pipe organ full registration in a cathedral",
    feature: "pipe organ stops and a long cathedral reverb",
    layers: [keys("pipe", "pipe")],
    fx: [
      [
        "reverb",
        { mix: 0.35, size: 0.95, fade: 6, lowpass: 6000, predelay: 0.04 },
      ],
    ],
    knobs: [
      knob(
        "Tone",
        [1000, 12000, 7000],
        { "keys.tone": null },
        "brightness",
        "exp",
      ),
      knob("Wind", [0, 1, 0.25], { "keys.noise": null }, "wind noise"),
      knob("Size", [0, 1, 0.95], { "reverb.size": null }, "building size"),
      knob("Space", [0, 0.8, 0.35], { "reverb.mix": null }, "reverb level"),
    ],
  },
  {
    name: "flute-pipes",
    category: "keys",
    tags: ["organ", "pipe", "flute", "chapel", "soft"],
    desc: "soft gedackt and flute pipes with tremulant and chiff",
    feature: "pipe organ flute stops with tremulant",
    layers: [keys("pipe", "flutes")],
    fx: [["reverb", { mix: 0.3, size: 0.8, fade: 3.5, lowpass: 7000 }]],
    knobs: [
      knob("Tremulant", [0, 1, 0.4], { "keys.trem": null }, "tremulant depth"),
      knob(
        "Tone",
        [1000, 12000, 7000],
        { "keys.tone": null },
        "brightness",
        "exp",
      ),
      knob("Wind", [0, 1, 0.25], { "keys.noise": null }, "wind noise"),
      knob("Space", [0, 0.8, 0.3], { "reverb.mix": null }, "reverb"),
    ],
  },
];
