/** Lead presets: mono and poly leads, sync, FM, supersaw, played leads. */
import { engine, knob, synth, type PresetSpec } from "../build.ts";

export const LEAD: readonly PresetSpec[] = [
  {
    name: "saw-lead",
    category: "lead",
    tags: ["classic", "mono", "glide", "analog", "vibrato"],
    desc: "classic two-saw mono lead with delayed vibrato and a dotted echo",
    feature: "filter envelope, vibrato and glide on two detuned saws",
    mono: true,
    layers: [
      synth("sawtooth", {
        unison: 2,
        detune: 0.1,
        spread: 0.3,
        attack: 0.005,
        decay: 0.25,
        sustain: 0.75,
        release: 0.15,
        lpf: 1600,
        lpq: 3,
        lpenv: 2.5,
        lpdecay: 0.3,
        lpsustain: 0.35,
        vib: 5.5,
        vibmod: 0.15,
      }),
    ],
    fx: [
      [
        "delay",
        {
          beats: 0.75,
          feedback: 0.35,
          mix: 0.18,
          highcut: 4000,
          pingpong: true,
        },
      ],
      ["reverb", { mix: 0.15, size: 0.5, fade: 1.5 }],
    ],
    knobs: [
      knob(
        "Bright",
        [300, 6000, 1600],
        { "synth.lpf": null },
        "filter cutoff",
        "exp",
      ),
      knob(
        "Bite",
        [0, 5, 2.5],
        { "synth.lpenv": null },
        "how far each note opens the filter",
      ),
      knob(
        "Vibrato",
        [0, 1, 0.15],
        { "synth.vibmod": null },
        "vibrato depth, in semitones",
      ),
      knob(
        "Space",
        [0, 0.5, 0.18],
        { "delay.mix": null, "reverb.mix": [0, 0.35] },
        "echo and room",
      ),
    ],
  },
  {
    name: "square-lead",
    category: "lead",
    tags: ["chip", "retro", "pwm", "hollow"],
    desc: "hollow pulse lead whose width breathes under a slow LFO",
    feature: "pulse width modulation (pwrate, pwsweep)",
    mono: true,
    layers: [
      synth("pulse", {
        pw: 0.5,
        pwrate: 0.6,
        pwsweep: 0.3,
        attack: 0.004,
        sustain: 0.85,
        release: 0.1,
        lpf: 3500,
        lpq: 1,
        vib: 5,
        vibmod: 0.08,
      }),
    ],
    fx: [
      ["chorus", { rate: 0.5, depth: 0.25, mix: 0.25 }],
      ["delay", { beats: 0.5, feedback: 0.3, mix: 0.12, highcut: 4000 }],
    ],
    knobs: [
      knob(
        "Width",
        [0.05, 0.5, 0.5],
        { "synth.pw": null },
        "pulse width: thin and nasal to hollow",
      ),
      knob(
        "Breath",
        [0, 1, 0.3],
        { "synth.pwsweep": null },
        "depth of the width LFO",
      ),
      knob(
        "Rate",
        [0.1, 8, 0.6],
        { "synth.pwrate": null },
        "width LFO speed (Hz)",
        "exp",
      ),
      knob("Tone", [500, 9000, 3500], { "synth.lpf": null }, "low-pass", "exp"),
    ],
  },
  {
    name: "sync-lead",
    category: "lead",
    tags: ["sync", "aggressive", "80s", "sweep"],
    desc: "tearing hard-sync style lead from a pitch-swept FM pair",
    feature: "pitch envelope on the FM modulator ratio for a sync-sweep tear",
    mono: true,
    layers: [
      synth("sawtooth", {
        attack: 0.003,
        sustain: 0.85,
        release: 0.12,
        fm: 2.5,
        fmh: 2,
        fmattack: 0,
        fmdecay: 0.35,
        fmsustain: 0.3,
        lpf: 5000,
        lpq: 1.5,
      }),
    ],
    fx: [
      ["distort", { type: "soft", drive: 1, mix: 0.4, tone: 7000 }],
      ["filter", { type: "lpf", cutoff: 7000, resonance: 0 }, "tame"],
      ["delay", { beats: 0.375, feedback: 0.3, mix: 0.15, highcut: 4000 }],
    ],
    knobs: [
      knob(
        "Tear",
        [0, 8, 2.5],
        { "synth.fm": null },
        "FM index: how hard the tone tears",
      ),
      knob(
        "Sweep",
        [0.05, 1.5, 0.35],
        { "synth.fmdecay": null },
        "how long the tear sweeps after each note",
        "exp",
      ),
      knob("Ratio", [1, 6, 2], { "synth.fmh": null }, "modulator ratio"),
      knob("Drive", [0, 4, 1], { "distort.drive": null }, "saturation"),
    ],
  },
  {
    name: "supersaw-lead",
    category: "lead",
    tags: ["trance", "edm", "unison", "wide", "big"],
    desc: "seven-saw trance lead, wide and bright, with ping-pong echo and hall",
    feature: "seven-voice unison with stereo spread",
    layers: [
      synth("supersaw", {
        unison: 7,
        detune: 0.3,
        spread: 0.85,
        attack: 0.008,
        decay: 0.3,
        sustain: 0.8,
        release: 0.25,
        lpf: 4500,
        lpq: 1,
        hpf: 120,
      }),
    ],
    fx: [
      [
        "delay",
        {
          beats: 0.75,
          feedback: 0.35,
          mix: 0.18,
          highcut: 5000,
          pingpong: true,
        },
      ],
      ["reverb", { mix: 0.22, size: 0.75, fade: 2.5, lowpass: 7000 }],
    ],
    knobs: [
      knob(
        "Detune",
        [0, 1, 0.3],
        { "synth.detune": null },
        "spread between the saws",
      ),
      knob(
        "Width",
        [0, 1, 0.85],
        { "synth.spread": null },
        "stereo spread of the saws",
      ),
      knob(
        "Bright",
        [800, 12000, 4500],
        { "synth.lpf": null },
        "low-pass",
        "exp",
      ),
      knob(
        "Space",
        [0, 0.5, 0.22],
        { "reverb.mix": null, "delay.mix": [0, 0.35] },
        "hall and echo",
      ),
    ],
  },
  {
    name: "fm-lead",
    category: "lead",
    tags: ["fm", "dx", "glassy", "digital", "80s"],
    desc: "glassy DX-style lead, bright attack and a mellow sustain",
    feature: "FM index envelope at a 3:1 ratio",
    mono: true,
    layers: [
      synth("sine", {
        attack: 0.003,
        decay: 0.4,
        sustain: 0.8,
        release: 0.2,
        fm: 2.2,
        fmh: 3,
        fmattack: 0,
        fmdecay: 0.5,
        fmsustain: 0.35,
        vib: 5.5,
        vibmod: 0.1,
      }),
    ],
    fx: [
      ["chorus", { rate: 0.4, depth: 0.3, mix: 0.3 }],
      ["reverb", { mix: 0.2, size: 0.55, fade: 1.8 }],
    ],
    knobs: [
      knob("Shine", [0, 6, 2.2], { "synth.fm": null }, "FM index: brightness"),
      knob(
        "Ratio",
        [1, 7, 3],
        { "synth.fmh": null },
        "modulator ratio: integer is tuned, between is metallic",
      ),
      knob(
        "Fade",
        [0.05, 2, 0.5],
        { "synth.fmdecay": null },
        "how fast the attack mellows",
        "exp",
      ),
      knob("Space", [0, 0.5, 0.2], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "screamer",
    category: "lead",
    tags: ["rock", "distorted", "guitar", "solo"],
    desc: "saw through a tube head and 4x12 cab: a singing distorted solo lead",
    feature: "amp head and cabinet simulation on a synth",
    mono: true,
    layers: [
      synth("sawtooth", {
        attack: 0.004,
        sustain: 0.9,
        release: 0.2,
        lpf: 3000,
        vib: 5.5,
        vibmod: 0.2,
        unison: 2,
        detune: 0.06,
      }),
    ],
    fx: [
      [
        "head",
        {
          type: "lead",
          gain: 6,
          bass: 4,
          mid: 6,
          treble: 5,
          master: 5,
          level: 8,
        },
      ],
      ["cab", { type: "4x12", mic: 0.3 }],
      ["delay", { beats: 0.75, feedback: 0.3, mix: 0.15, highcut: 3500 }],
      ["reverb", { mix: 0.15, size: 0.5 }],
    ],
    knobs: [
      knob("Gain", [0, 10, 6], { "head.gain": null }, "amp gain"),
      knob("Mid", [0, 10, 6], { "head.mid": null }, "amp midrange push"),
      knob(
        "Vibrato",
        [0, 0.6, 0.2],
        { "synth.vibmod": null },
        "finger vibrato depth",
      ),
      knob("Echo", [0, 0.4, 0.15], { "delay.mix": null }, "echo level"),
    ],
  },
  {
    name: "whistle-lead",
    category: "lead",
    tags: ["soft", "sine", "flute", "pure"],
    desc: "pure, breathy sine lead with gentle vibrato",
    feature: "noise blended into the oscillator for breath",
    mono: true,
    layers: [
      synth("sine", {
        attack: 0.04,
        sustain: 0.9,
        release: 0.2,
        noise: 0.06,
        vib: 5,
        vibmod: 0.12,
        lpf: 6000,
      }),
    ],
    fx: [
      ["delay", { beats: 0.5, feedback: 0.3, mix: 0.15, highcut: 4000 }],
      ["reverb", { mix: 0.25, size: 0.6, fade: 2 }],
    ],
    knobs: [
      knob("Breath", [0, 0.3, 0.06], { "synth.noise": null }, "breath noise"),
      knob(
        "Vibrato",
        [0, 0.5, 0.12],
        { "synth.vibmod": null },
        "vibrato depth",
      ),
      knob(
        "Swell",
        [0.002, 0.5, 0.04],
        { "synth.attack": null },
        "attack time",
        "exp",
      ),
      knob("Space", [0, 0.6, 0.25], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "acid-lead",
    category: "lead",
    tags: ["acid", "resonant", "squelch", "techno"],
    desc: "high acid line: ladder resonance screaming over a saw",
    feature: "ladder filter accent and envelope up high",
    mono: true,
    layers: [
      synth("sawtooth", {
        attack: 0.002,
        decay: 0.2,
        sustain: 0.4,
        release: 0.08,
        lpf: 700,
        lpq: 14,
        lpenv: 3,
        lpdecay: 0.15,
        lpsustain: 0.1,
        ftype: "ladder",
        faccent: 1.2,
      }),
    ],
    fx: [
      ["distort", { type: "diode", drive: 1.4, mix: 0.4, tone: 7000 }],
      ["filter", { type: "hpf", cutoff: 30 }, "dcblock"],
      ["delay", { beats: 0.75, feedback: 0.4, mix: 0.18, highcut: 3500 }],
    ],
    knobs: [
      knob(
        "Cutoff",
        [150, 4000, 700],
        { "synth.lpf": null },
        "ladder cutoff",
        "exp",
      ),
      knob("Squelch", [2, 26, 14], { "synth.lpq": null }, "resonance"),
      knob("Env", [0, 6, 3], { "synth.lpenv": null }, "filter envelope"),
      knob("Drive", [0, 5, 1.4], { "distort.drive": null }, "diode drive"),
    ],
  },
  {
    name: "talk-lead",
    category: "lead",
    tags: ["vowel", "talkbox", "funk", "formant"],
    desc: "saw lead talking through a vowel morph that follows each note",
    feature: "vowel formant filter morphed by a per-note envelope",
    mono: true,
    layers: [
      synth("sawtooth", {
        attack: 0.005,
        sustain: 0.9,
        release: 0.15,
        unison: 2,
        detune: 0.08,
        vib: 5,
        vibmod: 0.1,
      }),
    ],
    fx: [
      ["vowel", { vowel: "u", to: "a", mix: 0.85, morph: 0.2 }],
      ["filter", { type: "lpf", cutoff: 5000 }],
      ["chorus", { rate: 0.5, depth: 0.3, mix: 0.25 }],
    ],
    mods: [
      {
        id: "wah",
        type: "adsr",
        params: { attack: 0.12, decay: 0.3, sustain: 0.4, release: 0.2 },
        to: "vowel.morph",
        amount: 0.7,
      },
    ],
    knobs: [
      knob(
        "Mouth",
        [0, 1, 0.2],
        { "vowel.morph": null },
        "resting vowel, u toward a",
      ),
      knob(
        "Talk",
        [0, 1, 0.85],
        { "vowel.mix": null },
        "how much of the vowel filter you hear",
      ),
      knob(
        "Tone",
        [1000, 10000, 5000],
        { "filter.cutoff": null },
        "low-pass",
        "exp",
      ),
      knob("Chorus", [0, 0.6, 0.25], { "chorus.mix": null }, "chorus width"),
    ],
  },
  {
    name: "sax-lead",
    category: "lead",
    tags: ["sax", "jazz", "physical", "breath", "growl"],
    desc: "breathy tenor sax with growl on demand",
    feature: "physically modeled reed: breath pressure and growl",
    mono: true,
    layers: [
      engine("wind", "sax", {}, { params: { breath: 0.65, growl: 0.1 } }),
    ],
    fx: [["reverb", { mix: 0.18, size: 0.45, fade: 1.4 }]],
    knobs: [
      knob(
        "Breath",
        [0.2, 1, 0.65],
        { "wind.breath": null },
        "blowing pressure: soft to overblown",
      ),
      knob("Growl", [0, 1, 0.1], { "wind.growl": null }, "throat growl"),
      knob("Air", [0, 0.5, 0.08], { "wind.noise": null }, "breath noise"),
      knob("Room", [0, 0.5, 0.18], { "reverb.mix": null }, "room"),
    ],
  },
];
