/** Arp, FX, texture, percussion and init presets. */
import { engine, keys, knob, synth, type PresetSpec } from "../build.ts";

const verb = (mix: number, size = 0.7, fade = 2.5) =>
  ["reverb", { mix, size, fade, lowpass: 7000 }] as const;

export const ARP: readonly PresetSpec[] = [
  {
    name: "trance-gate",
    category: "arp",
    tags: ["trance", "gate", "rhythmic", "pad", "sixteenths"],
    desc: "supersaw chords chopped into sixteenths by a synced gate",
    feature: "tempo-synced tremolo used as a trance gate",
    layers: [
      synth("supersaw", {
        unison: 5,
        detune: 0.2,
        spread: 0.8,
        attack: 0.01,
        sustain: 1,
        release: 0.4,
        lpf: 3500,
        lpq: 1,
      }),
    ],
    fx: [
      ["tremolo", { shape: "square", sync: 0.25, depth: 1, skew: 0.3 }],
      [
        "delay",
        {
          beats: 0.75,
          feedback: 0.3,
          mix: 0.15,
          highcut: 5000,
          pingpong: true,
        },
      ],
      verb(0.2),
    ],
    knobs: [
      knob(
        "Gate",
        [0, 1, 1],
        { "tremolo.depth": null },
        "how hard the gate chops",
      ),
      knob(
        "Step",
        [0.125, 1, 0.25],
        { "tremolo.sync": null },
        "gate step in beats",
        "exp",
      ),
      knob(
        "Shape",
        [0, 1, 0.3],
        { "tremolo.skew": null },
        "short stabs to long swells",
      ),
      knob(
        "Tone",
        [500, 10000, 3500],
        { "synth.lpf": null },
        "low-pass",
        "exp",
      ),
    ],
  },
  {
    name: "pulse-seq",
    category: "arp",
    tags: ["sequence", "berlin", "analog", "pulse", "delay"],
    desc: "Berlin-school pulse sequence: short notes multiplied by a dotted echo",
    feature: "filter envelope plus tempo-synced dotted delay feedback",
    guard: true,
    layers: [
      synth("pulse", {
        pw: 0.3,
        pwrate: 0.3,
        pwsweep: 0.2,
        attack: 0.001,
        decay: 0.18,
        sustain: 0,
        release: 0.1,
        lpf: 500,
        lpq: 6,
        lpenv: 3.5,
        lpdecay: 0.12,
        lpsustain: 0,
        ftype: "ladder",
      }),
    ],
    fx: [
      ["filter", { type: "hpf", cutoff: 30 }, "dcblock"],
      [
        "delay",
        {
          beats: 0.75,
          feedback: 0.55,
          mix: 0.3,
          highcut: 4000,
          pingpong: true,
        },
      ],
      verb(0.15),
    ],
    knobs: [
      knob(
        "Cutoff",
        [100, 4000, 500],
        { "synth.lpf": null },
        "resting cutoff",
        "exp",
      ),
      knob("Snap", [0, 6, 3.5], { "synth.lpenv": null }, "envelope snap"),
      knob(
        "Repeats",
        [0, 0.85, 0.55],
        { "delay.feedback": null },
        "echo repeats",
      ),
      knob("Echo", [0, 0.6, 0.3], { "delay.mix": null }, "echo level"),
    ],
  },
  {
    name: "pluck-arp",
    category: "arp",
    tags: ["arp", "pluck", "edm", "bright"],
    desc: "bright pluck tuned for fast arpeggios, with stereo echoes",
    feature: "snappy filter envelope with velocity to brightness",
    guard: true,
    layers: [
      synth("sawtooth", {
        unison: 2,
        detune: 0.08,
        spread: 0.6,
        attack: 0.001,
        decay: 0.15,
        sustain: 0,
        release: 0.12,
        lpf: 900,
        lpq: 1.5,
        lpenv: 3.5,
        lpdecay: 0.1,
        lpsustain: 0,
      }),
    ],
    fx: [
      ["filter", { type: "lpf", cutoff: 7000 }, "soften"],
      [
        "delay",
        { beats: 0.5, feedback: 0.4, mix: 0.22, highcut: 5000, pingpong: true },
      ],
      verb(0.18),
    ],
    knobs: [
      knob("Snap", [0, 6, 4], { "synth.lpenv": null }, "envelope snap"),
      knob(
        "Length",
        [0.03, 0.8, 0.15],
        { "synth.decay": null },
        "note length",
        "exp",
      ),
      knob("Reso", [0, 15, 3], { "synth.lpq": null }, "filter resonance"),
      knob("Echo", [0, 0.6, 0.22], { "delay.mix": null }, "echo"),
    ],
  },
  {
    name: "fm-sequence",
    category: "arp",
    tags: ["fm", "sequence", "digital", "metallic"],
    desc: "metallic FM blips that turn glassy with velocity",
    feature: "two-operator FM with a fast index envelope",
    layers: [
      synth("sine", {
        attack: 0.001,
        decay: 0.2,
        sustain: 0,
        release: 0.1,
        fm: 5,
        fmh: 2.01,
        fmdecay: 0.08,
        fmsustain: 0,
        fm2: 1.5,
        fmh2: 7,
      }),
    ],
    fx: [
      [
        "delay",
        {
          beats: 0.375,
          feedback: 0.4,
          mix: 0.2,
          highcut: 6000,
          pingpong: true,
        },
      ],
      verb(0.15),
    ],
    knobs: [
      knob("Metal", [0, 10, 5], { "synth.fm": null }, "FM index"),
      knob("Ratio", [0.5, 8, 2.01], { "synth.fmh": null }, "modulator ratio"),
      knob(
        "Length",
        [0.03, 1, 0.2],
        { "synth.decay": null },
        "blip length",
        "exp",
      ),
      knob("Echo", [0, 0.6, 0.2], { "delay.mix": null }, "echo"),
    ],
  },
  {
    name: "pumping-chords",
    category: "arp",
    tags: ["house", "sidechain", "pump", "chords", "edm"],
    desc: "house chords ducking on every beat",
    feature: "a clocked sidechain envelope pumping the level",
    layers: [
      synth("supersaw", {
        unison: 4,
        detune: 0.15,
        spread: 0.8,
        attack: 0.01,
        sustain: 1,
        release: 0.3,
        lpf: 2500,
      }),
    ],
    fx: [
      ["tremolo", { sync: 1, depth: 0.85, skew: 0.9, phase: 0.75 }],
      verb(0.15),
    ],
    knobs: [
      knob(
        "Pump",
        [0, 1, 0.85],
        { "tremolo.depth": null },
        "how deep each beat ducks",
      ),
      knob(
        "Rate",
        [0.25, 2, 1],
        { "tremolo.sync": null },
        "pump length in beats",
        "exp",
      ),
      knob(
        "Tone",
        [400, 10000, 2500],
        { "synth.lpf": null },
        "low-pass",
        "exp",
      ),
      knob("Space", [0, 0.6, 0.15], { "reverb.mix": null }, "reverb"),
    ],
  },
];

export const FX: readonly PresetSpec[] = [
  {
    name: "noise-riser",
    category: "fx",
    tags: ["riser", "sweep", "noise", "build", "edm"],
    desc: "white-noise riser: a band-pass sweeping up over the held note",
    feature: "slow filter envelope on noise, with a phaser",
    layers: [
      synth("white", {
        attack: 3,
        sustain: 1,
        release: 1,
        bpf: 300,
        bpq: 4,
        bpenv: 5,
        bpattack: 4,
        bpsustain: 1,
      }),
    ],
    fx: [["phaser", { rate: 0.5, depth: 0.6 }], verb(0.35, 0.8, 4)],
    knobs: [
      knob(
        "Rise",
        [0.5, 10, 4],
        { "synth.bpattack": null },
        "rise time",
        "exp",
      ),
      knob(
        "Sweep",
        [0, 7, 5],
        { "synth.bpenv": null },
        "how far the band climbs",
      ),
      knob("Focus", [0, 15, 4], { "synth.bpq": null }, "band resonance"),
      knob("Space", [0, 0.8, 0.35], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "pitch-riser",
    category: "fx",
    tags: ["riser", "pitch", "build", "tension"],
    desc: "detuned saws gliding up two octaves",
    feature: "pitch envelope on supersaw unison",
    layers: [
      synth("supersaw", {
        unison: 5,
        detune: 0.3,
        spread: 0.9,
        attack: 2,
        sustain: 1,
        release: 1,
        penv: 24,
        pattack: 4,
        psustain: 1,
        lpf: 4000,
      }),
    ],
    fx: [verb(0.35, 0.8, 4)],
    knobs: [
      knob("Climb", [0, 36, 24], { "synth.penv": null }, "semitones it rises"),
      knob("Rise", [0.5, 10, 4], { "synth.pattack": null }, "rise time", "exp"),
      knob("Spread", [0, 1, 0.3], { "synth.detune": null }, "detune"),
      knob("Space", [0, 0.8, 0.35], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "sub-drop",
    category: "fx",
    tags: ["impact", "drop", "boom", "sub", "trailer"],
    desc: "sub drop: a sine diving from a punch into the floor",
    feature: "downward pitch envelope with saturation",
    range: [36, 48],
    layers: [
      synth("sine", {
        attack: 0.001,
        decay: 2,
        sustain: 0,
        release: 0.5,
        penv: 24,
        pdecay: 1.2,
        psustain: 0,
      }),
    ],
    fx: [["distort", { drive: 2, mix: 0.5 }], verb(0.2, 0.7, 3)],
    knobs: [
      knob("Drop", [0, 48, 24], { "synth.penv": null }, "how far it falls"),
      knob("Fall", [0.1, 4, 1.2], { "synth.pdecay": null }, "fall time", "exp"),
      knob("Boom", [0.3, 6, 2], { "synth.decay": null }, "length", "exp"),
      knob("Grit", [0, 6, 2], { "distort.drive": null }, "saturation"),
    ],
  },
  {
    name: "impact",
    category: "fx",
    tags: ["impact", "hit", "trailer", "cinematic", "boom"],
    desc: "cinematic impact: a gong, a sub boom and a huge hall",
    feature: "layered modal gong with a pitched sub",
    range: [36, 48],
    guard: true,
    layers: [
      engine("modal", "gong"),
      synth(
        "sine",
        {
          attack: 0.001,
          decay: 1.5,
          sustain: 0,
          release: 0.5,
          penv: 12,
          pdecay: 0.3,
          psustain: 0,
        },
        { gain: 0.7 },
      ),
    ],
    fx: [verb(0.4, 0.95, 5)],
    knobs: [
      knob("Metal", [0, 1, 0.6], { "modal.hardness": null }, "gong strike"),
      knob("Boom", [0, 1.5, 0.7], { "synth.gain": null }, "sub boom level"),
      knob("Ring", [0.5, 30, 6], { "modal.ring": null }, "gong ring", "exp"),
      knob("Hall", [0, 0.9, 0.4], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "laser",
    category: "fx",
    tags: ["laser", "zap", "sci-fi", "retro"],
    desc: "sci-fi zap: a square diving in pitch",
    feature: "fast pitch envelope (zap)",
    layers: [
      synth("square", {
        attack: 0.001,
        decay: 0.3,
        sustain: 0,
        release: 0.1,
        penv: 36,
        pdecay: 0.15,
        psustain: 0,
        lpf: 5000,
      }),
    ],
    fx: [
      [
        "delay",
        {
          beats: 0.375,
          feedback: 0.4,
          mix: 0.25,
          highcut: 6000,
          pingpong: true,
        },
      ],
    ],
    knobs: [
      knob("Zap", [0, 48, 36], { "synth.penv": null }, "pitch dive"),
      knob(
        "Speed",
        [0.02, 1, 0.15],
        { "synth.pdecay": null },
        "dive time",
        "exp",
      ),
      knob(
        "Tone",
        [500, 12000, 5000],
        { "synth.lpf": null },
        "low-pass",
        "exp",
      ),
      knob("Echo", [0, 0.6, 0.25], { "delay.mix": null }, "echo"),
    ],
  },
  {
    name: "siren",
    category: "fx",
    tags: ["siren", "dub", "reggae", "lfo"],
    desc: "dub siren wailing under a spring echo",
    feature: "LFO on pitch with a dub delay",
    mono: true,
    layers: [
      synth("square", {
        attack: 0.01,
        sustain: 1,
        release: 0.5,
        vib: 2,
        vibmod: 7,
        lpf: 3000,
      }),
    ],
    fx: [
      ["delay", { beats: 0.75, feedback: 0.6, mix: 0.35, highcut: 2500 }],
      verb(0.25, 0.5),
    ],
    knobs: [
      knob(
        "Wail",
        [0, 12, 7],
        { "synth.vibmod": null },
        "how far the pitch swings",
      ),
      knob("Speed", [0.1, 10, 2], { "synth.vib": null }, "siren speed", "exp"),
      knob(
        "Repeats",
        [0, 0.85, 0.6],
        { "delay.feedback": null },
        "dub echo repeats",
      ),
      knob("Echo", [0, 0.7, 0.35], { "delay.mix": null }, "echo"),
    ],
  },
  {
    name: "downlifter",
    category: "fx",
    tags: ["downlifter", "sweep", "noise", "transition"],
    desc: "noise sweep falling away after a drop",
    feature: "falling filter envelope on pink noise",
    layers: [
      synth("pink", {
        attack: 0.01,
        decay: 3,
        sustain: 0,
        release: 1,
        lpf: 300,
        lpq: 3,
        lpenv: 6,
        lpdecay: 2.5,
        lpsustain: 0,
      }),
    ],
    fx: [
      ["filter", { type: "hpf", cutoff: 30 }, "dcblock"],
      verb(0.35, 0.85, 4),
    ],
    knobs: [
      knob(
        "Fall",
        [0.3, 8, 2.5],
        { "synth.lpdecay": null },
        "fall time",
        "exp",
      ),
      knob("Sweep", [0, 7, 6], { "synth.lpenv": null }, "sweep height"),
      knob("Focus", [0, 15, 3], { "synth.lpq": null }, "resonance"),
      knob("Space", [0, 0.8, 0.35], { "reverb.mix": null }, "reverb"),
    ],
  },
];

export const TEXTURE: readonly PresetSpec[] = [
  {
    name: "deep-drone",
    category: "texture",
    tags: ["drone", "dark", "ambient", "slow", "evolving"],
    desc: "slow dark drone breathing under a randomly drifting filter",
    feature: "random-shape autofilter and long hall on detuned saws",
    layers: [
      synth("supersaw", {
        unison: 6,
        detune: 0.1,
        spread: 0.9,
        attack: 3,
        sustain: 1,
        release: 4,
        lpf: 400,
        lpq: 2,
        ftype: "ladder",
      }),
    ],
    fx: [
      ["filter", { type: "hpf", cutoff: 30 }, "dcblock"],
      [
        "autofilter",
        {
          type: "lpf",
          cutoff: 500,
          resonance: 0.3,
          depth: 1,
          sync: 16,
          shape: "random",
        },
      ],
      verb(0.45, 0.95, 6),
    ],
    knobs: [
      knob(
        "Dark",
        [100, 3000, 500],
        { "autofilter.cutoff": null },
        "filter center",
        "exp",
      ),
      knob(
        "Drift",
        [0, 4, 1],
        { "autofilter.depth": null },
        "how far it drifts (octaves)",
      ),
      knob(
        "Breath",
        [2, 64, 16],
        { "autofilter.sync": null },
        "drift cycle in beats",
        "exp",
      ),
      knob("Space", [0, 0.9, 0.45], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "tanpura-drone",
    category: "texture",
    tags: ["tanpura", "indian", "drone", "buzz", "world"],
    desc: "tanpura drone with its shimmering bridge buzz",
    feature: "physical string with a jawari bridge",
    layers: [engine("string", "tanpura")],
    fx: [verb(0.3, 0.7, 4)],
    range: [36, 55],
    knobs: [
      knob("Buzz", [0, 1, 0.6], { "string.buzz": null }, "jawari buzz"),
      knob("Tone", [0, 1, 0.6], { "string.bright": null }, "brightness"),
      knob("Ring", [1, 30, 8], { "string.ring": null }, "ring", "exp"),
      knob("Space", [0, 0.8, 0.3], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "grain-swarm",
    category: "texture",
    tags: ["granular", "swarm", "experimental", "dense"],
    desc: "dense swarm of tiny grains scattered across the stereo field",
    feature: "granular engine: density, jitter and spray",
    layers: [engine("granular", "swarm")],
    fx: [verb(0.35, 0.85, 4)],
    knobs: [
      knob(
        "Grain",
        [0.005, 0.3, 0.04],
        { "granular.grain": null },
        "grain length",
        "exp",
      ),
      knob(
        "Density",
        [1, 16, 8],
        { "granular.overlap": null },
        "grains at once",
        "exp",
      ),
      knob(
        "Scatter",
        [0, 1, 0.7],
        { "granular.jitter": null },
        "timing jitter",
      ),
      knob("Space", [0, 0.9, 0.35], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "dust-bed",
    category: "texture",
    tags: ["granular", "dust", "lofi", "crackle", "ambient"],
    desc: "dusty granular bed with vinyl crackle",
    feature: "granular dust preset with bitcrush",
    layers: [
      engine("granular", "dust"),
      synth(
        "crackle",
        { attack: 0.5, sustain: 1, release: 1, lpf: 6000 },
        { gain: 0.15 },
      ),
    ],
    fx: [["crush", { bits: 10, mix: 0.5 }], verb(0.3, 0.7, 3)],
    knobs: [
      knob(
        "Dust",
        [0, 0.5, 0.15],
        { "synth.gain": null },
        "vinyl crackle level",
      ),
      knob("Bits", [4, 16, 10], { "crush.bits": null }, "bit depth"),
      knob(
        "Scatter",
        [0, 1, 0.5],
        { "granular.jitter": null },
        "grain scatter",
      ),
      knob("Space", [0, 0.9, 0.3], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "wind-wash",
    category: "texture",
    tags: ["wind", "noise", "ambient", "weather", "sfx"],
    desc: "howling wind: resonant noise gusting under a slow filter",
    feature: "LFO on a resonant band-pass over brown noise",
    layers: [
      synth("brown", { attack: 2, sustain: 1, release: 3, bpf: 600, bpq: 8 }),
    ],
    fx: [
      [
        "autofilter",
        {
          type: "bpf",
          cutoff: 700,
          resonance: 0.6,
          depth: 1,
          sync: 8,
          shape: "random",
        },
      ],
      verb(0.4, 0.9, 5),
    ],
    knobs: [
      knob(
        "Howl",
        [200, 3000, 700],
        { "autofilter.cutoff": null },
        "howl pitch",
        "exp",
      ),
      knob(
        "Gust",
        [0, 4, 1],
        { "autofilter.depth": null },
        "gust depth (octaves)",
      ),
      knob(
        "Whistle",
        [0, 0.95, 0.6],
        { "autofilter.resonance": null },
        "whistle",
      ),
      knob("Space", [0, 0.9, 0.4], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "bowed-metal",
    category: "texture",
    tags: ["cinematic", "metal", "eerie", "bowed", "horror"],
    desc: "eerie bowed metal: crotales ringing into a long hall",
    feature: "modal resonator with very long ring and a phaser",
    layers: [engine("modal", "crotales", {}, { params: { ring: 6 } })],
    fx: [["phaser", { rate: 0.15, depth: 0.5 }], verb(0.5, 0.95, 6)],
    knobs: [
      knob("Ring", [1, 30, 6], { "modal.ring": null }, "ring", "exp"),
      knob(
        "Strike",
        [0, 1, 0.2],
        { "modal.hardness": null },
        "strike hardness",
      ),
      knob("Swirl", [0, 1, 0.5], { "phaser.depth": null }, "phaser swirl"),
      knob("Space", [0, 0.95, 0.5], { "reverb.mix": null }, "reverb"),
    ],
  },
];

export const PERC: readonly PresetSpec[] = [
  ...(
    [
      [
        "tabla",
        "tabla",
        "tabla: the singing bayan and crisp dayan",
        ["tabla", "indian", "world", "hand-drum"],
      ],
      [
        "frame-drum",
        "daf",
        "daf frame drum with jingles",
        ["daf", "frame", "persian", "world"],
      ],
      [
        "bodhran",
        "bodhran",
        "Irish bodhran, deep and woody",
        ["bodhran", "irish", "folk", "frame"],
      ],
      [
        "timpani",
        "timpani",
        "orchestral timpani in a hall",
        ["timpani", "orchestral", "cinematic"],
      ],
      [
        "xylophone",
        "xylophone",
        "dry, bright xylophone",
        ["xylophone", "wood", "mallet"],
      ],
      [
        "kenong",
        "kenong",
        "deep gamelan kettle gong",
        ["gamelan", "gong", "indonesian"],
      ],
    ] as const
  ).map(([name, preset, desc, tags]): PresetSpec => ({
    name,
    category: "perc",
    tags: [...tags, "modal"],
    desc,
    feature: "modal resonator: strike hardness, position and damping",
    guard: true,
    layers: [engine("modal", preset)],
    fx: [verb(0.15, 0.5, 1.5)],
    knobs: [
      knob("Hit", [0, 1, 0.5], { "modal.hardness": null }, "strike hardness"),
      knob(
        "Spot",
        [0, 1, 0.3],
        { "modal.position": null },
        "where it is struck",
      ),
      knob("Damp", [0, 1, 0], { "modal.damp": null }, "hand damping"),
      knob("Room", [0, 0.6, 0.15], { "reverb.mix": null }, "room"),
    ],
  })),
];

/** One plain starting point per engine. */
export const INIT: readonly PresetSpec[] = [
  {
    name: "init-synth",
    category: "init",
    tags: ["init", "synth", "blank", "subtractive"],
    desc: "one saw through an open low-pass: build anything from here",
    feature: "the full synth voice, every control at a neutral value",
    layers: [
      synth("sawtooth", {
        attack: 0.005,
        sustain: 0.8,
        release: 0.2,
        lpf: 8000,
      }),
    ],
    knobs: [
      knob(
        "Cutoff",
        [100, 16000, 8000],
        { "synth.lpf": null },
        "low-pass cutoff",
        "exp",
      ),
      knob("Reso", [0, 20, 0], { "synth.lpq": null }, "resonance"),
      knob(
        "Attack",
        [0.001, 2, 0.005],
        { "synth.attack": null },
        "attack",
        "exp",
      ),
      knob(
        "Release",
        [0.01, 4, 0.2],
        { "synth.release": null },
        "release",
        "exp",
      ),
    ],
  },
  {
    name: "init-fm",
    category: "init",
    tags: ["init", "fm", "blank"],
    desc: "a two-operator FM sine with the index at zero",
    feature: "FM operators ready to turn up",
    layers: [
      synth("sine", {
        attack: 0.005,
        sustain: 0.8,
        release: 0.3,
        fm: 0,
        fmh: 1,
      }),
    ],
    knobs: [
      knob("Index", [0, 10, 0], { "synth.fm": null }, "FM index"),
      knob("Ratio", [0.5, 8, 1], { "synth.fmh": null }, "modulator ratio"),
      knob(
        "Attack",
        [0.001, 2, 0.005],
        { "synth.attack": null },
        "attack",
        "exp",
      ),
      knob(
        "Release",
        [0.01, 4, 0.3],
        { "synth.release": null },
        "release",
        "exp",
      ),
    ],
  },
  {
    name: "init-keys",
    category: "init",
    tags: ["init", "keys", "piano", "blank"],
    desc: "the modeled grand, dry",
    feature: "keys engine with no effects",
    guard: true,
    layers: [keys("grand", "grand")],
    fx: [
      [
        "compressor",
        { threshold: -30, ratio: 2.5, attack: 0.01, release: 0.25, makeup: 10 },
      ],
    ],
    knobs: [
      knob(
        "Tone",
        [1000, 12000, 8000],
        { "keys.tone": null },
        "brightness",
        "exp",
      ),
      knob("Hammer", [0, 1, 0.5], { "keys.hardness": null }, "hammer hardness"),
      knob("Release", [0.1, 4, 1], { "keys.release": null }, "release", "exp"),
      knob("Decay", [0.3, 3, 1], { "keys.decay": null }, "decay"),
    ],
  },
  {
    name: "init-string",
    category: "init",
    tags: ["init", "string", "physical", "blank"],
    desc: "the plucked string model, dry",
    feature: "physical string controls at neutral",
    guard: true,
    layers: [engine("string", "nylon")],
    knobs: [
      knob(
        "Position",
        [0.02, 0.5, 0.15],
        { "string.pos": null },
        "pluck position",
      ),
      knob("Tone", [0, 1, 0.6], { "string.bright": null }, "brightness"),
      knob("Ring", [0.2, 10, 3], { "string.ring": null }, "ring", "exp"),
      knob("Damp", [0, 1, 0.4], { "string.damp": null }, "damping"),
    ],
  },
  {
    name: "init-modal",
    category: "init",
    tags: ["init", "modal", "mallet", "blank"],
    desc: "the modal resonator as a plain marimba bar, dry",
    feature: "modal resonator controls at neutral",
    layers: [engine("modal", "marimba")],
    knobs: [
      knob(
        "Hardness",
        [0, 1, 0.4],
        { "modal.hardness": null },
        "mallet hardness",
      ),
      knob(
        "Position",
        [0, 1, 0.42],
        { "modal.position": null },
        "strike position",
      ),
      knob("Ring", [0.1, 10, 1.6], { "modal.ring": null }, "ring", "exp"),
      knob("Tilt", [0, 2, 0.9], { "modal.tilt": null }, "upper partials"),
    ],
  },
  {
    name: "init-wind",
    category: "init",
    tags: ["init", "wind", "physical", "blank"],
    desc: "the wind model as a plain flute, dry",
    feature: "physical wind controls at neutral",
    mono: true,
    range: [60, 84],
    layers: [engine("wind", "flute")],
    knobs: [
      knob(
        "Breath",
        [0.2, 1, 0.6],
        { "wind.breath": null },
        "blowing pressure",
      ),
      knob("Noise", [0, 0.5, 0.08], { "wind.noise": null }, "breath noise"),
      knob("Growl", [0, 1, 0], { "wind.growl": null }, "growl"),
      knob("Flutter", [0, 1, 0], { "wind.flutter": null }, "flutter tongue"),
    ],
  },
  {
    name: "init-voice",
    category: "init",
    tags: ["init", "sing", "voice", "blank"],
    desc: "the singing voice on aah, dry",
    feature: "formant voice controls at neutral",
    layers: [engine("sing", "aah")],
    knobs: [
      knob("Vowel", [0, 1, 1], { "sing.morph": null }, "vowel morph"),
      knob("Breath", [0, 0.6, 0.12], { "sing.breath": null }, "breathiness"),
      knob("Bright", [0, 1, 0.5], { "sing.bright": null }, "brightness"),
      knob("Formant", [-6, 6, 0], { "sing.formant": null }, "formant shift"),
    ],
  },
  {
    name: "init-granular",
    category: "init",
    tags: ["init", "granular", "blank"],
    desc: "the granular player holding its source, dry",
    feature: "granular controls at neutral",
    layers: [engine("granular", "hold")],
    knobs: [
      knob(
        "Grain",
        [0.01, 0.5, 0.1],
        { "granular.grain": null },
        "grain length",
        "exp",
      ),
      knob(
        "Density",
        [1, 16, 4],
        { "granular.overlap": null },
        "grains at once",
        "exp",
      ),
      knob(
        "Scatter",
        [0, 1, 0.2],
        { "granular.jitter": null },
        "timing jitter",
      ),
      knob("Spread", [0, 1, 0.5], { "granular.spread": null }, "stereo spread"),
    ],
  },
];
