/** Strings, brass, wind and vox presets. */
import { engine, knob, synth, type PresetSpec } from "../build.ts";

const hall = (mix: number) =>
  [
    "reverb",
    { mix, size: 0.8, fade: 3, lowpass: 6500, predelay: 0.03 },
  ] as const;

const bowKnobs = (space: number) =>
  [
    knob(
      "Pressure",
      [0, 1, 0.5],
      { "string.pressure": null },
      "bow pressure: airy to gritty",
    ),
    knob("Bow", [0, 1, 0.6], { "string.speed": null }, "bow speed"),
    knob("Vibrato", [0, 12, 5], { "string.vib": null }, "vibrato rate (Hz)"),
    knob("Hall", [0, 0.8, space], { "reverb.mix": null }, "hall"),
  ] as const;

export const STRINGS: readonly PresetSpec[] = [
  {
    name: "violin-section",
    category: "strings",
    tags: ["strings", "ensemble", "violins", "orchestral", "physical"],
    desc: "violin section, bowed, in a scoring hall",
    feature: "bowed string model: pressure, bow speed, vibrato",
    layers: [engine("string", "violins")],
    fx: [hall(0.28)],
    knobs: bowKnobs(0.28),
  },
  {
    name: "cello-section",
    category: "strings",
    tags: ["strings", "ensemble", "cellos", "orchestral", "low"],
    desc: "warm cello section",
    feature: "bowed string model, low register",
    range: [36, 64],
    layers: [engine("string", "cellos")],
    fx: [hall(0.28)],
    knobs: bowKnobs(0.28),
  },
  {
    name: "solo-violin",
    category: "strings",
    tags: ["strings", "solo", "violin", "expressive"],
    desc: "expressive solo violin with delayed vibrato",
    feature: "bowed string model with vibrato depth",
    mono: true,
    range: [55, 84],
    layers: [engine("string", "violin")],
    fx: [hall(0.22)],
    knobs: bowKnobs(0.22),
  },
  {
    name: "solo-cello",
    category: "strings",
    tags: ["strings", "solo", "cello", "expressive"],
    desc: "rich solo cello",
    feature: "bowed string model, solo",
    mono: true,
    range: [36, 64],
    layers: [engine("string", "cello")],
    fx: [hall(0.22)],
    knobs: bowKnobs(0.22),
  },
  {
    name: "pizzicato",
    category: "strings",
    tags: ["strings", "pizz", "plucked", "orchestral", "short"],
    desc: "plucked string section",
    feature: "string model played pizzicato",
    layers: [engine("string", "pizz")],
    fx: [hall(0.25)],
    knobs: [
      knob("Tone", [0, 1, 0.6], { "string.bright": null }, "brightness"),
      knob("Ring", [0.1, 4, 0.8], { "string.ring": null }, "ring", "exp"),
      knob("Damp", [0, 1, 0.4], { "string.damp": null }, "damping"),
      knob("Hall", [0, 0.8, 0.25], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "tremolo-strings",
    category: "strings",
    tags: ["strings", "tremolo", "tension", "cinematic"],
    desc: "tense bowed tremolo strings",
    feature: "string model bowed tremolo",
    layers: [engine("string", "trem")],
    fx: [hall(0.3)],
    knobs: bowKnobs(0.3),
  },
  {
    name: "erhu",
    category: "strings",
    tags: ["erhu", "chinese", "world", "solo", "bowed"],
    desc: "Chinese two-string erhu, nasal and singing",
    feature: "bowed string world preset",
    mono: true,
    range: [60, 84],
    layers: [engine("string", "erhu")],
    fx: [hall(0.2)],
    knobs: bowKnobs(0.2),
  },
  {
    name: "synth-strings",
    category: "strings",
    tags: ["synth", "strings", "80s", "solina", "ensemble"],
    desc: "string machine: sawtooth ensemble through a thick chorus",
    feature: "unison saws into a triple-depth ensemble chorus",
    layers: [
      synth("supersaw", {
        unison: 4,
        detune: 0.12,
        spread: 0.8,
        attack: 0.25,
        sustain: 0.9,
        release: 1,
        lpf: 3500,
        hpf: 200,
      }),
    ],
    fx: [["chorus", { rate: 0.7, depth: 0.6, mix: 0.5 }], hall(0.25)],
    knobs: [
      knob("Ensemble", [0, 1, 0.5], { "chorus.mix": null }, "ensemble chorus"),
      knob("Swell", [0.01, 2, 0.25], { "synth.attack": null }, "attack", "exp"),
      knob(
        "Tone",
        [800, 10000, 3500],
        { "synth.lpf": null },
        "low-pass",
        "exp",
      ),
      knob("Hall", [0, 0.8, 0.25], { "reverb.mix": null }, "hall"),
    ],
  },
];

export const BRASS: readonly PresetSpec[] = [
  {
    name: "synth-brass",
    category: "brass",
    tags: ["synth", "brass", "80s", "stab", "poly"],
    desc: "80s poly brass: saws with a filter swell on every chord",
    feature: "filter envelope with a slow attack (brass swell)",
    layers: [
      synth("sawtooth", {
        unison: 3,
        detune: 0.12,
        spread: 0.6,
        attack: 0.04,
        decay: 0.4,
        sustain: 0.8,
        release: 0.25,
        lpf: 900,
        lpq: 1,
        lpenv: 2.5,
        lpattack: 0.08,
        lpdecay: 0.4,
        lpsustain: 0.4,
      }),
    ],
    fx: [["chorus", { rate: 0.4, depth: 0.25, mix: 0.2 }], hall(0.18)],
    knobs: [
      knob(
        "Brass",
        [0, 5, 2.5],
        { "synth.lpenv": null },
        "filter swell amount",
      ),
      knob(
        "Swell",
        [0.005, 0.5, 0.08],
        { "synth.lpattack": null },
        "how slowly the swell opens",
        "exp",
      ),
      knob(
        "Tone",
        [200, 4000, 900],
        { "synth.lpf": null },
        "resting cutoff",
        "exp",
      ),
      knob("Hall", [0, 0.6, 0.18], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "brass-stab",
    category: "brass",
    tags: ["stab", "house", "rave", "short"],
    desc: "short rave brass stab with plate reverb",
    feature: "fast filter envelope on detuned saws",
    layers: [
      synth("supersaw", {
        unison: 5,
        detune: 0.2,
        spread: 0.7,
        attack: 0.005,
        decay: 0.25,
        sustain: 0.1,
        release: 0.2,
        lpf: 1200,
        lpq: 1.5,
        lpenv: 3,
        lpdecay: 0.15,
        lpsustain: 0,
      }),
    ],
    fx: [["reverb", { mix: 0.22, size: 0.5, fade: 1.2, lowpass: 7000 }]],
    knobs: [
      knob("Punch", [0, 6, 3], { "synth.lpenv": null }, "filter punch"),
      knob(
        "Length",
        [0.05, 1, 0.25],
        { "synth.decay": null },
        "stab length",
        "exp",
      ),
      knob("Tone", [300, 5000, 1200], { "synth.lpf": null }, "cutoff", "exp"),
      knob("Plate", [0, 0.6, 0.22], { "reverb.mix": null }, "plate reverb"),
    ],
  },
  {
    name: "trumpet",
    category: "brass",
    tags: ["trumpet", "brass", "jazz", "physical", "solo"],
    desc: "modeled trumpet with lip buzz and breath",
    feature: "physical brass model: breath pressure",
    mono: true,
    range: [55, 79],
    layers: [engine("wind", "trumpet")],
    fx: [hall(0.18)],
    knobs: [
      knob(
        "Breath",
        [0.2, 1, 0.6],
        { "wind.breath": null },
        "blowing pressure: mellow to blaring",
      ),
      knob("Air", [0, 0.4, 0.08], { "wind.noise": null }, "breath noise"),
      knob("Growl", [0, 1, 0], { "wind.growl": null }, "growl"),
      knob("Hall", [0, 0.6, 0.18], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "muted-trumpet",
    category: "brass",
    tags: ["trumpet", "harmon", "mute", "jazz", "miles"],
    desc: "harmon-muted trumpet, intimate and buzzy",
    feature: "brass model with a harmon mute and wah",
    mono: true,
    range: [55, 79],
    layers: [engine("wind", "harmon")],
    fx: [hall(0.18)],
    knobs: [
      knob(
        "Breath",
        [0.2, 1, 0.6],
        { "wind.breath": null },
        "blowing pressure",
      ),
      knob("Wah", [0, 1, 1], { "wind.wah": null }, "mute opening"),
      knob("Air", [0, 0.4, 0.08], { "wind.noise": null }, "breath noise"),
      knob("Hall", [0, 0.6, 0.18], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "trombone",
    category: "brass",
    tags: ["trombone", "brass", "low", "physical"],
    desc: "warm modeled trombone",
    feature: "physical brass model, low register",
    mono: true,
    range: [40, 65],
    layers: [engine("wind", "trombone")],
    fx: [hall(0.18)],
    knobs: [
      knob(
        "Breath",
        [0.2, 1, 0.6],
        { "wind.breath": null },
        "blowing pressure",
      ),
      knob("Air", [0, 0.4, 0.08], { "wind.noise": null }, "breath noise"),
      knob("Growl", [0, 1, 0], { "wind.growl": null }, "growl"),
      knob("Hall", [0, 0.6, 0.18], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "french-horn",
    category: "brass",
    tags: ["horn", "orchestral", "cinematic", "warm"],
    desc: "noble French horn in a hall",
    feature: "physical brass model with a hand-stopped bell",
    mono: true,
    range: [45, 70],
    layers: [engine("wind", "horn")],
    fx: [hall(0.3)],
    knobs: [
      knob(
        "Breath",
        [0.2, 1, 0.55],
        { "wind.breath": null },
        "blowing pressure",
      ),
      knob("Air", [0, 0.4, 0.08], { "wind.noise": null }, "breath noise"),
      knob("Flutter", [0, 1, 0], { "wind.flutter": null }, "flutter tongue"),
      knob("Hall", [0, 0.8, 0.3], { "reverb.mix": null }, "hall"),
    ],
  },
];

const windKnobs = (space: number) =>
  [
    knob(
      "Breath",
      [0.2, 1, 0.6],
      { "wind.breath": null },
      "blowing pressure: soft to overblown",
    ),
    knob("Air", [0, 0.5, 0.08], { "wind.noise": null }, "breath noise"),
    knob("Flutter", [0, 1, 0], { "wind.flutter": null }, "flutter tongue"),
    knob("Room", [0, 0.6, space], { "reverb.mix": null }, "room"),
  ] as const;

export const WIND: readonly PresetSpec[] = [
  ...(
    [
      [
        "flute",
        "flute",
        "concert flute, airy and pure",
        ["flute", "orchestral", "airy"],
        [60, 91],
      ],
      [
        "clarinet",
        "clarinet",
        "woody clarinet with a hollow low register",
        ["clarinet", "reed", "jazz"],
        [50, 84],
      ],
      [
        "oboe",
        "oboe",
        "plaintive double-reed oboe",
        ["oboe", "reed", "orchestral"],
        [58, 86],
      ],
      [
        "shakuhachi",
        "shakuhachi",
        "breathy Japanese bamboo flute",
        ["shakuhachi", "japanese", "world", "breathy"],
        [55, 84],
      ],
      [
        "pan-flute",
        "panpipe",
        "Andean pan pipes",
        ["panpipe", "world", "andean", "airy"],
        [60, 88],
      ],
      [
        "bansuri",
        "bansuri",
        "Indian bamboo flute with ornamented breath",
        ["bansuri", "indian", "world"],
        [55, 84],
      ],
    ] as const
  ).map(([name, preset, desc, tags, range]): PresetSpec => ({
    name,
    category: "wind",
    tags: [...tags, "physical"],
    desc,
    feature: "physical wind model: breath pressure, noise and flutter",
    mono: true,
    range,
    layers: [engine("wind", preset)],
    fx: [["reverb", { mix: 0.2, size: 0.55, fade: 1.8, lowpass: 7000 }]],
    knobs: windKnobs(0.2),
  })),
];

export const VOX: readonly PresetSpec[] = [
  {
    name: "aah-choir",
    category: "vox",
    tags: ["choir", "aah", "ensemble", "cinematic"],
    desc: "mixed choir singing aah in a cathedral",
    feature: "formant singing engine: vowel morph and ensemble",
    layers: [engine("sing", "aah")],
    fx: [["reverb", { mix: 0.35, size: 0.9, fade: 4.5, lowpass: 6000 }]],
    knobs: [
      knob("Vowel", [0, 1, 1], { "sing.morph": null }, "vowel morph"),
      knob("Breath", [0, 0.6, 0.12], { "sing.breath": null }, "breathiness"),
      knob("Bright", [0, 1, 0.5], { "sing.bright": null }, "brightness"),
      knob("Space", [0, 0.8, 0.35], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "ooh-choir",
    category: "vox",
    tags: ["choir", "ooh", "soft", "ensemble"],
    desc: "soft ooh choir",
    feature: "formant singing engine, closed vowel",
    layers: [engine("sing", "oohchoir")],
    fx: [["reverb", { mix: 0.35, size: 0.9, fade: 4.5, lowpass: 6000 }]],
    knobs: [
      knob("Vowel", [0, 1, 1], { "sing.morph": null }, "vowel morph"),
      knob("Breath", [0, 0.6, 0.12], { "sing.breath": null }, "breathiness"),
      knob(
        "Formant",
        [-6, 6, 0],
        { "sing.formant": null },
        "formant shift: bigger or smaller singers",
      ),
      knob("Space", [0, 0.8, 0.35], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "soprano",
    category: "vox",
    tags: ["solo", "soprano", "opera", "vibrato"],
    desc: "solo soprano with operatic vibrato",
    feature: "formant singing engine, solo voice",
    mono: true,
    range: [60, 84],
    layers: [engine("sing", "soprano")],
    fx: [["reverb", { mix: 0.3, size: 0.8, fade: 3.5, lowpass: 7000 }]],
    knobs: [
      knob("Vibrato", [0, 1, 0.3], { "sing.vibmod": null }, "vibrato depth"),
      knob("Breath", [0, 0.6, 0.12], { "sing.breath": null }, "breathiness"),
      knob("Bright", [0, 1, 0.5], { "sing.bright": null }, "brightness"),
      knob("Space", [0, 0.8, 0.3], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "throat-singer",
    category: "vox",
    tags: ["khoomei", "throat", "overtone", "drone", "world"],
    desc: "Tuvan khoomei: a drone with a whistling overtone melody",
    feature: "overtone singing: a resonant formant picks out harmonics",
    mono: true,
    range: [40, 55],
    layers: [engine("sing", "khoomei")],
    fx: [["reverb", { mix: 0.25, size: 0.7, fade: 3 }]],
    knobs: [
      knob(
        "Overtone",
        [0, 1, 0.7],
        { "sing.overtone": null },
        "level of the whistled overtone",
      ),
      knob(
        "Sub",
        [0, 1, 0],
        { "sing.sub": null },
        "kargyraa subharmonic growl",
      ),
      knob("Vowel", [0, 1, 1], { "sing.morph": null }, "vowel"),
      knob("Space", [0, 0.8, 0.25], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "glass-voices",
    category: "vox",
    tags: ["choir", "glass", "airy", "ethereal"],
    desc: "ethereal glassy voices with ringing formants",
    feature: "formant singing engine with ring modulation",
    layers: [engine("sing", "glass")],
    fx: [["reverb", { mix: 0.4, size: 0.9, fade: 5 }]],
    knobs: [
      knob(
        "Ring",
        [0, 1, 0.3],
        { "sing.ring": null },
        "ring-modulated shimmer",
      ),
      knob("Breath", [0, 0.6, 0.2], { "sing.breath": null }, "breathiness"),
      knob("Bright", [0, 1, 0.6], { "sing.bright": null }, "brightness"),
      knob("Space", [0, 0.9, 0.4], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "talkbox-voice",
    category: "vox",
    tags: ["vocoder", "robot", "daft", "talkbox", "synth"],
    desc: "talkbox vocoder: the synth speaks through the built-in voice",
    feature: "vocoder engine: a saw carrier shaped by a speech modulator",
    layers: [engine("vocoder", "talkbox")],
    fx: [
      ["filter", { type: "lpf", cutoff: 7000, resonance: 0.1 }],
      ["chorus", { rate: 0.4, depth: 0.25, mix: 0.2 }],
      ["reverb", { mix: 0.15, size: 0.5 }],
    ],
    knobs: [
      knob(
        "Tone",
        [800, 12000, 7000],
        { "filter.cutoff": null },
        "how bright the robot speaks",
        "exp",
      ),
      knob("Chorus", [0, 0.7, 0.2], { "chorus.mix": null }, "chorus width"),
      knob("Wobble", [0, 1, 0.25], { "chorus.depth": null }, "chorus wobble"),
      knob("Space", [0, 0.6, 0.15], { "reverb.mix": null }, "reverb"),
    ],
  },
];
