/** Pad presets: warm, glass, evolving, choir, granular and string pads. */
import { engine, knob, synth, type PresetSpec } from "../build.ts";

export const PAD: readonly PresetSpec[] = [
  {
    name: "warm-pad",
    category: "pad",
    tags: ["analog", "warm", "soft", "unison", "chords"],
    desc: "soft analog pad of six detuned saws under a slow, rounded low-pass",
    feature: "six-voice unison, slow filter envelope and a chorus",
    layers: [
      synth("supersaw", {
        unison: 6,
        detune: 0.2,
        spread: 0.8,
        attack: 0.7,
        decay: 1,
        sustain: 0.85,
        release: 1.6,
        lpf: 1300,
        lpq: 0.7,
        lpenv: 1,
        lpattack: 1.2,
        lpdecay: 2,
        lpsustain: 0.5,
      }),
    ],
    fx: [
      ["chorus", { rate: 0.3, depth: 0.35, mix: 0.3 }],
      ["reverb", { mix: 0.3, size: 0.75, fade: 3.5, lowpass: 6000 }],
    ],
    knobs: [
      knob(
        "Warmth",
        [300, 5000, 1300],
        { "synth.lpf": null },
        "low-pass: darker to brighter",
        "exp",
      ),
      knob(
        "Bloom",
        [0.01, 3, 0.7],
        { "synth.attack": null },
        "how slowly chords swell in",
        "exp",
      ),
      knob(
        "Width",
        [0, 0.6, 0.2],
        { "synth.detune": null },
        "detune between the saws",
      ),
      knob("Space", [0, 0.7, 0.3], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "glass-pad",
    category: "pad",
    tags: ["fm", "glass", "airy", "bright", "digital"],
    desc: "shimmering FM glass pad with a slowly moving shine",
    feature: "FM at a 7:2 ratio with an LFO on the index",
    layers: [
      synth("sine", {
        attack: 0.6,
        sustain: 0.9,
        release: 2,
        fm: 1.2,
        fmh: 3.5,
        unison: 3,
        detune: 0.08,
        spread: 0.7,
      }),
    ],
    fx: [
      ["chorus", { rate: 0.2, depth: 0.4, mix: 0.3 }],
      ["filter", { type: "lpf", cutoff: 6000 }],
      ["reverb", { mix: 0.35, size: 0.85, fade: 4, lowpass: 7000 }],
    ],
    mods: [
      {
        id: "shine",
        type: "lfo",
        params: { shape: "sine", sync: 8 },
        to: "synth.fm",
        amount: 0.6,
      },
    ],
    knobs: [
      knob("Shine", [0, 4, 1.2], { "synth.fm": null }, "FM index: glassiness"),
      knob(
        "Motion",
        [0, 1, 0.6],
        { "shine.depth": null },
        "how much the shine moves over eight beats",
      ),
      knob(
        "Tone",
        [1500, 12000, 6000],
        { "filter.cutoff": null },
        "low-pass",
        "exp",
      ),
      knob("Space", [0, 0.8, 0.35], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "evolving-pad",
    category: "pad",
    tags: ["evolving", "motion", "cinematic", "filter", "lfo"],
    desc: "slowly evolving pad: a filter that drifts over bars and a phaser",
    feature: "slow synced autofilter plus phaser for long movement",
    layers: [
      synth("supersaw", {
        unison: 5,
        detune: 0.25,
        spread: 0.9,
        attack: 1.2,
        sustain: 0.9,
        release: 2.5,
        lpf: 2500,
        lpq: 1,
      }),
      synth(
        "triangle",
        { attack: 1, sustain: 0.9, release: 2.5 },
        { gain: 0.5, id: "body" },
      ),
    ],
    fx: [
      [
        "autofilter",
        {
          type: "lpf",
          cutoff: 1200,
          resonance: 0.35,
          depth: 2,
          sync: 16,
          shape: "tri",
        },
      ],
      ["phaser", { rate: 0.1, depth: 0.6, center: 1200, sweep: 1500 }],
      ["reverb", { mix: 0.35, size: 0.85, fade: 5, lowpass: 6000 }],
    ],
    knobs: [
      knob(
        "Drift",
        [0, 4, 2],
        { "autofilter.depth": null },
        "how far the filter wanders, in octaves",
      ),
      knob(
        "Cycle",
        [2, 32, 16],
        { "autofilter.sync": null },
        "filter sweep length in beats",
        "exp",
      ),
      knob("Phase", [0, 1, 0.6], { "phaser.depth": null }, "phaser depth"),
      knob("Space", [0, 0.8, 0.35], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "choir-pad",
    category: "pad",
    tags: ["choir", "vocal", "aah", "cinematic", "formant"],
    desc: "a soft ensemble choir pad singing aah, morphing toward ooh",
    feature: "formant singing engine with a vowel morph",
    layers: [
      engine("sing", "choir", {}, { params: { morph: 1, breath: 0.15 } }),
    ],
    fx: [["reverb", { mix: 0.35, size: 0.8, fade: 4, lowpass: 6000 }]],
    knobs: [
      knob("Vowel", [0, 1, 1], { "sing.morph": null }, "vowel morph"),
      knob("Breath", [0, 0.6, 0.15], { "sing.breath": null }, "breathiness"),
      knob("Bright", [0, 1, 0.5], { "sing.bright": null }, "vocal brightness"),
      knob("Space", [0, 0.8, 0.35], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "string-pad",
    category: "pad",
    tags: ["strings", "ensemble", "lush", "physical"],
    desc: "a bowed string-section pad with slow attack and a warm hall",
    feature: "bowed string model: bow pressure and speed",
    layers: [
      engine(
        "string",
        "violins",
        { attack: 0.5 },
        { params: { pressure: 0.45, speed: 0.5 } },
      ),
    ],
    fx: [
      ["chorus", { rate: 0.25, depth: 0.25, mix: 0.2 }],
      ["reverb", { mix: 0.3, size: 0.8, fade: 3.5, lowpass: 6000 }],
    ],
    knobs: [
      knob(
        "Pressure",
        [0, 1, 0.45],
        { "string.pressure": null },
        "bow pressure: airy to gritty",
      ),
      knob("Bow", [0, 1, 0.5], { "string.speed": null }, "bow speed"),
      knob(
        "Mute",
        [0, 1, 0],
        { "string.sord": null },
        "con sordino: veiled strings",
      ),
      knob("Space", [0, 0.8, 0.3], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "grain-cloud",
    category: "pad",
    tags: ["granular", "cloud", "ambient", "texture"],
    desc: "granular cloud scanning a held pad: soft, wide and shimmering",
    feature: "granular engine: grain size, overlap, jitter and spray",
    layers: [
      engine(
        "granular",
        "cloud",
        {},
        { params: { grain: 0.12, overlap: 6, jitter: 0.5, spread: 0.7 } },
      ),
    ],
    fx: [["reverb", { mix: 0.3, size: 0.85, fade: 4 }]],
    knobs: [
      knob(
        "Grain",
        [0.01, 0.5, 0.12],
        { "granular.grain": null },
        "grain length",
        "exp",
      ),
      knob(
        "Density",
        [1, 16, 6],
        { "granular.overlap": null },
        "grains overlapping at once",
        "exp",
      ),
      knob(
        "Scatter",
        [0, 1, 0.5],
        { "granular.jitter": null },
        "timing jitter",
      ),
      knob(
        "Shimmer",
        [0, 1, 0],
        { "granular.shimmer": null },
        "octave-up shimmer grains",
      ),
    ],
  },
  {
    name: "dark-pad",
    category: "pad",
    tags: ["dark", "cinematic", "low", "drone"],
    desc: "dark low pad: detuned saws through a ladder filter and a long hall",
    feature: "ladder filter with resonance and a slow random drift",
    layers: [
      synth("supersaw", {
        unison: 4,
        detune: 0.15,
        spread: 0.7,
        attack: 1.5,
        sustain: 1,
        release: 3,
        lpf: 600,
        lpq: 4,
        ftype: "ladder",
      }),
    ],
    fx: [
      ["filter", { type: "hpf", cutoff: 30 }, "dcblock"],
      [
        "autofilter",
        {
          type: "lpf",
          cutoff: 700,
          resonance: 0.2,
          depth: 1,
          sync: 16,
          shape: "random",
        },
      ],
      ["reverb", { mix: 0.4, size: 0.9, fade: 6, lowpass: 4000 }],
    ],
    range: [36, 64],
    knobs: [
      knob(
        "Shade",
        [150, 3000, 600],
        { "synth.lpf": null },
        "ladder cutoff",
        "exp",
      ),
      knob("Growl", [0, 15, 4], { "synth.lpq": null }, "ladder resonance"),
      knob(
        "Drift",
        [0, 3, 1],
        { "autofilter.depth": null },
        "random filter drift",
      ),
      knob("Space", [0, 0.9, 0.4], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "bloom-pad",
    category: "pad",
    tags: ["shimmer", "bloom", "ambient", "octave"],
    desc: "pad that blooms into an octave-up shimmer behind every chord",
    feature: "bloom effect: delayed harmonic swell",
    layers: [
      synth("triangle", {
        attack: 0.4,
        sustain: 0.9,
        release: 2,
        unison: 3,
        detune: 0.1,
        spread: 0.7,
        lpf: 4000,
      }),
    ],
    fx: [
      ["bloom", { amount: 0.5, harm: 2, delay: 0.6, time: 1.5 }],
      ["reverb", { mix: 0.35, size: 0.85, fade: 4, lowpass: 7000 }],
    ],
    knobs: [
      knob(
        "Bloom",
        [0, 1, 0.5],
        { "bloom.amount": null },
        "level of the harmonic swell",
      ),
      knob(
        "Harmonic",
        [1, 4, 2],
        { "bloom.harm": null },
        "which harmonic blooms",
      ),
      knob(
        "Wait",
        [0, 3, 0.6],
        { "bloom.delay": null },
        "seconds before the bloom starts",
      ),
      knob("Space", [0, 0.8, 0.35], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "pwm-pad",
    category: "pad",
    tags: ["pwm", "analog", "80s", "juno", "chorus"],
    desc: "Juno-style PWM strings: pulse width sweeping under a lush chorus",
    feature: "pulse width modulation into a stereo chorus",
    layers: [
      synth("pulse", {
        pw: 0.4,
        pwrate: 0.4,
        pwsweep: 0.35,
        attack: 0.5,
        sustain: 0.9,
        release: 1.5,
        lpf: 2500,
        lpq: 0.5,
      }),
    ],
    fx: [
      ["chorus", { rate: 0.5, depth: 0.5, mix: 0.45 }],
      ["reverb", { mix: 0.25, size: 0.7, fade: 3 }],
    ],
    knobs: [
      knob(
        "Sweep",
        [0, 1, 0.35],
        { "synth.pwsweep": null },
        "pulse width sweep depth",
      ),
      knob(
        "Rate",
        [0.05, 4, 0.4],
        { "synth.pwrate": null },
        "sweep speed (Hz)",
        "exp",
      ),
      knob("Chorus", [0, 1, 0.45], { "chorus.mix": null }, "chorus"),
      knob("Tone", [500, 8000, 2500], { "synth.lpf": null }, "low-pass", "exp"),
    ],
  },
  {
    name: "vowel-pad",
    category: "pad",
    tags: ["vowel", "formant", "motion", "vocal"],
    desc: "saw pad whose vowels slowly shift from ah to oh over the bar",
    feature: "vowel formant filter swept by a slow LFO",
    layers: [
      synth("supersaw", {
        unison: 4,
        detune: 0.18,
        spread: 0.8,
        attack: 0.6,
        sustain: 0.9,
        release: 1.8,
      }),
    ],
    fx: [
      ["vowel", { vowel: "a", to: "o", mix: 0.8, morph: 0.5 }],
      ["filter", { type: "lpf", cutoff: 4500 }],
      ["reverb", { mix: 0.3, size: 0.75, fade: 3.5 }],
    ],
    mods: [
      {
        id: "lfo",
        type: "lfo",
        params: { shape: "sine", sync: 8 },
        to: "vowel.morph",
        amount: 0.5,
      },
    ],
    knobs: [
      knob("Vowel", [0, 1, 0.5], { "vowel.morph": null }, "center vowel"),
      knob(
        "Motion",
        [0, 1, 1],
        { "lfo.depth": null },
        "how far the vowel moves",
      ),
      knob(
        "Cycle",
        [1, 32, 8],
        { "lfo.sync": null },
        "vowel sweep length in beats",
        "exp",
      ),
      knob("Space", [0, 0.8, 0.3], { "reverb.mix": null }, "hall"),
    ],
  },
];
