/** Pluck and mallet presets: synth plucks, guitars, harps, bells, mallets. */
import { engine, knob, synth, type PresetSpec } from "../build.ts";

const verb = (mix: number, size = 0.6) =>
  ["reverb", { mix, size, fade: 2, lowpass: 7000 }] as const;

export const PLUCK: readonly PresetSpec[] = [
  {
    name: "house-pluck",
    category: "pluck",
    tags: ["edm", "house", "pluck", "short", "unison"],
    desc: "bright detuned house pluck with ping-pong echo",
    feature: "three-voice unison and a snappy filter envelope",
    guard: true,
    layers: [
      synth("supersaw", {
        unison: 3,
        detune: 0.15,
        spread: 0.7,
        attack: 0.001,
        decay: 0.3,
        sustain: 0,
        release: 0.2,
        lpf: 700,
        lpq: 2,
        lpenv: 4,
        lpdecay: 0.15,
        lpsustain: 0,
      }),
    ],
    fx: [
      [
        "delay",
        {
          beats: 0.75,
          feedback: 0.35,
          mix: 0.2,
          highcut: 5000,
          pingpong: true,
        },
      ],
      verb(0.18),
    ],
    knobs: [
      knob(
        "Snap",
        [0, 6, 4],
        { "synth.lpenv": null },
        "how bright each pluck starts",
      ),
      knob(
        "Length",
        [0.05, 1.5, 0.3],
        { "synth.decay": null },
        "pluck length",
        "exp",
      ),
      knob(
        "Tone",
        [200, 4000, 700],
        { "synth.lpf": null },
        "resting cutoff",
        "exp",
      ),
      knob("Echo", [0, 0.5, 0.2], { "delay.mix": null }, "ping-pong echo"),
    ],
  },
  {
    name: "glass-pluck",
    category: "pluck",
    tags: ["fm", "glass", "bright", "digital"],
    desc: "glassy FM pluck with a short bright attack",
    feature: "FM index envelope at a 5:1 ratio",
    layers: [
      synth("sine", {
        attack: 0.001,
        decay: 0.45,
        sustain: 0,
        release: 0.3,
        fm: 3,
        fmh: 5,
        fmdecay: 0.15,
        fmsustain: 0,
      }),
    ],
    fx: [
      [
        "delay",
        { beats: 0.5, feedback: 0.3, mix: 0.15, highcut: 5000, pingpong: true },
      ],
      verb(0.2),
    ],
    knobs: [
      knob("Glass", [0, 8, 3], { "synth.fm": null }, "FM index: glassiness"),
      knob("Ratio", [1, 9, 5], { "synth.fmh": null }, "modulator ratio"),
      knob(
        "Length",
        [0.1, 2, 0.45],
        { "synth.decay": null },
        "pluck length",
        "exp",
      ),
      knob("Space", [0, 0.6, 0.2], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "nylon-guitar",
    category: "pluck",
    tags: ["guitar", "acoustic", "nylon", "physical", "classical"],
    desc: "warm nylon-string classical guitar",
    feature: "physical string model: pluck position and brightness",
    layers: [engine("string", "nylon")],
    fx: [verb(0.15, 0.45)],
    knobs: [
      knob(
        "Position",
        [0.02, 0.5, 0.15],
        { "string.pos": null },
        "pluck position: bridge is twangy",
      ),
      knob("Tone", [0, 1, 0.6], { "string.bright": null }, "brightness"),
      knob("Ring", [0.2, 10, 3], { "string.ring": null }, "sustain", "exp"),
      knob("Room", [0, 0.5, 0.15], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "steel-guitar",
    category: "pluck",
    tags: ["guitar", "acoustic", "steel", "folk", "strum"],
    desc: "bright steel-string acoustic guitar",
    feature: "physical string model with body resonance",
    guard: true,
    layers: [engine("string", "steel")],
    fx: [["chorus", { rate: 0.4, depth: 0.15, mix: 0.12 }], verb(0.15, 0.45)],
    knobs: [
      knob(
        "Position",
        [0.02, 0.5, 0.15],
        { "string.pos": null },
        "pluck position",
      ),
      knob("Tone", [0, 1, 0.6], { "string.bright": null }, "brightness"),
      knob("Mute", [0, 1, 0], { "string.mute": null }, "palm mute"),
      knob("Room", [0, 0.5, 0.15], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "clean-electric",
    category: "pluck",
    tags: ["guitar", "electric", "clean", "chorus", "amp"],
    desc: "clean electric guitar through a chiming amp and chorus",
    feature: "string model into an amp head and 2x12 cab",
    layers: [engine("string", "electric")],
    fx: [
      ["head", { type: "chime", gain: 3, bass: 5, mid: 5, treble: 6 }],
      ["cab", { type: "2x12", mic: 0.4 }],
      ["chorus", { rate: 0.6, depth: 0.3, mix: 0.3 }],
      verb(0.15, 0.5),
    ],
    knobs: [
      knob(
        "Gain",
        [0, 8, 3],
        { "head.gain": null },
        "amp gain: clean to edge of breakup",
      ),
      knob("Treble", [0, 10, 6], { "head.treble": null }, "amp treble"),
      knob("Chorus", [0, 0.7, 0.3], { "chorus.mix": null }, "chorus"),
      knob("Room", [0, 0.5, 0.15], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "crunch-guitar",
    category: "pluck",
    tags: ["guitar", "electric", "crunch", "rock", "amp"],
    desc: "crunchy rhythm guitar through an overdrive pedal and a 4x12",
    feature: "pedal, amp head and cabinet chain on a string model",
    layers: [engine("string", "electric", {}, { params: { mute: 0.15 } })],
    fx: [
      ["stomp", { type: "od", gain: 5, tone: 0.55 }],
      ["head", { type: "crunch", gain: 5, mid: 6 }],
      ["cab", { type: "4x12", mic: 0.3 }],
      verb(0.1, 0.4),
    ],
    knobs: [
      knob("Drive", [0, 10, 5], { "stomp.gain": null }, "overdrive pedal gain"),
      knob("Amp", [0, 10, 5], { "head.gain": null }, "amp gain"),
      knob("Mute", [0, 1, 0.15], { "string.mute": null }, "palm mute"),
      knob("Mid", [0, 10, 6], { "head.mid": null }, "amp mids"),
    ],
  },
  {
    name: "harp",
    category: "pluck",
    tags: ["harp", "orchestral", "glissando", "physical"],
    desc: "concert harp, round and ringing",
    feature: "plucked string model with long ring",
    guard: true,
    layers: [engine("string", "harp")],
    fx: [["filter", { type: "hpf", cutoff: 35 }, "dcblock"], verb(0.25, 0.7)],
    knobs: [
      knob("Tone", [0, 1, 0.6], { "string.bright": null }, "brightness"),
      knob("Ring", [0.5, 20, 3], { "string.ring": null }, "ring time", "exp"),
      knob("Damp", [0, 1, 0.4], { "string.damp": null }, "string damping"),
      knob("Hall", [0, 0.7, 0.25], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "koto",
    category: "pluck",
    tags: ["koto", "japanese", "world", "physical"],
    desc: "Japanese koto with a bright, bending pluck",
    feature: "string model world preset",
    guard: true,
    layers: [engine("string", "koto")],
    fx: [verb(0.2, 0.55)],
    knobs: [
      knob(
        "Position",
        [0.02, 0.5, 0.15],
        { "string.pos": null },
        "pluck position",
      ),
      knob("Tone", [0, 1, 0.6], { "string.bright": null }, "brightness"),
      knob("Ring", [0.2, 10, 3], { "string.ring": null }, "ring", "exp"),
      knob("Room", [0, 0.6, 0.2], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "sitar",
    category: "pluck",
    tags: ["sitar", "indian", "world", "buzz", "drone"],
    desc: "sitar with its buzzing jawari bridge",
    feature: "string bridge buzz (jawari)",
    guard: true,
    layers: [engine("string", "sitar")],
    fx: [verb(0.2, 0.55)],
    knobs: [
      knob("Buzz", [0, 1, 0.6], { "string.buzz": null }, "jawari buzz"),
      knob("Tone", [0, 1, 0.6], { "string.bright": null }, "brightness"),
      knob("Ring", [0.5, 20, 4], { "string.ring": null }, "ring", "exp"),
      knob("Room", [0, 0.6, 0.2], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "banjo",
    category: "pluck",
    tags: ["banjo", "bluegrass", "country", "twang"],
    desc: "bright, twangy five-string banjo",
    feature: "string model with a drum-head body",
    guard: true,
    layers: [engine("string", "banjo")],
    fx: [verb(0.1, 0.4)],
    knobs: [
      knob("Twang", [0.02, 0.5, 0.1], { "string.pos": null }, "pluck position"),
      knob("Tone", [0, 1, 0.7], { "string.bright": null }, "brightness"),
      knob("Ring", [0.2, 6, 1.5], { "string.ring": null }, "ring", "exp"),
      knob("Room", [0, 0.5, 0.1], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "kalimba",
    category: "pluck",
    tags: ["kalimba", "thumb-piano", "african", "modal", "mallet"],
    desc: "warm kalimba tines with a woody box",
    feature: "modal resonator: strike hardness and position",
    layers: [engine("modal", "kalimba")],
    fx: [verb(0.2, 0.5)],
    knobs: [
      knob("Thumb", [0, 1, 0.4], { "modal.hardness": null }, "strike hardness"),
      knob("Ring", [0.1, 10, 1.6], { "modal.ring": null }, "ring time", "exp"),
      knob("Tone", [0, 2, 0.9], { "modal.tilt": null }, "upper partials"),
      knob("Room", [0, 0.6, 0.2], { "reverb.mix": null }, "room"),
    ],
  },
];

export const MALLET: readonly PresetSpec[] = [
  {
    name: "marimba",
    category: "mallet",
    tags: ["marimba", "wood", "mallet", "modal"],
    desc: "rosewood marimba with tuned resonator tubes",
    feature: "modal resonator: mallet hardness and strike position",
    layers: [engine("modal", "marimba")],
    fx: [verb(0.18, 0.5)],
    knobs: [
      knob(
        "Mallet",
        [0, 1, 0.4],
        { "modal.hardness": null },
        "mallet hardness",
      ),
      knob(
        "Strike",
        [0, 1, 0.42],
        { "modal.position": null },
        "strike position on the bar",
      ),
      knob("Ring", [0.1, 10, 1.6], { "modal.ring": null }, "ring time", "exp"),
      knob("Room", [0, 0.6, 0.18], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "vibraphone",
    category: "mallet",
    tags: ["vibes", "jazz", "motor", "tremolo", "modal"],
    desc: "jazz vibraphone with the motor's shimmering tremolo",
    feature: "modal resonator with motor depth (rotating discs)",
    layers: [engine("modal", "vibes", {}, { params: { motordepth: 0.5 } })],
    fx: [verb(0.22, 0.6)],
    knobs: [
      knob(
        "Motor",
        [0, 1, 0.5],
        { "modal.motordepth": null },
        "vibrato motor depth",
      ),
      knob(
        "Mallet",
        [0, 1, 0.4],
        { "modal.hardness": null },
        "mallet hardness",
      ),
      knob("Ring", [0.1, 20, 1.6], { "modal.ring": null }, "ring time", "exp"),
      knob("Room", [0, 0.6, 0.22], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "glockenspiel",
    category: "mallet",
    tags: ["glock", "bell", "bright", "orchestral"],
    desc: "bright orchestral glockenspiel",
    feature: "metal bar modal resonator",
    layers: [engine("modal", "glock")],
    fx: [verb(0.22, 0.6)],
    knobs: [
      knob(
        "Mallet",
        [0, 1, 0.5],
        { "modal.hardness": null },
        "mallet hardness",
      ),
      knob("Ring", [0.1, 20, 1.6], { "modal.ring": null }, "ring time", "exp"),
      knob("Tone", [0, 2, 0.9], { "modal.tilt": null }, "upper partials"),
      knob("Room", [0, 0.6, 0.22], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "tubular-bells",
    category: "mallet",
    tags: ["chimes", "bell", "church", "orchestral"],
    desc: "tubular chimes ringing in a big hall",
    feature: "inharmonic tube partials",
    layers: [engine("modal", "chimes")],
    fx: [verb(0.3, 0.85)],
    knobs: [
      knob(
        "Mallet",
        [0, 1, 0.5],
        { "modal.hardness": null },
        "mallet hardness",
      ),
      knob("Ring", [0.5, 30, 4], { "modal.ring": null }, "ring time", "exp"),
      knob("Damp", [0, 1, 0], { "modal.damp": null }, "hand damping"),
      knob("Hall", [0, 0.8, 0.3], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "fm-bells",
    category: "mallet",
    tags: ["fm", "bell", "dx", "digital", "inharmonic"],
    desc: "classic DX bell: an inharmonic FM ratio with a long ring",
    feature: "FM at an inharmonic 3.5:1 ratio",
    layers: [
      synth("sine", {
        attack: 0.001,
        decay: 2.5,
        sustain: 0,
        release: 1.5,
        fm: 3.5,
        fmh: 3.5,
        fmdecay: 1.5,
        fmsustain: 0,
      }),
    ],
    fx: [verb(0.3, 0.75)],
    knobs: [
      knob(
        "Strike",
        [0, 8, 3.5],
        { "synth.fm": null },
        "FM index: brightness of the strike",
      ),
      knob(
        "Metal",
        [1, 7, 3.5],
        { "synth.fmh": null },
        "ratio: integer tuned, between is clangorous",
      ),
      knob("Ring", [0.3, 8, 2.5], { "synth.decay": null }, "ring time", "exp"),
      knob("Hall", [0, 0.8, 0.3], { "reverb.mix": null }, "hall"),
    ],
  },
  {
    name: "steelpan",
    category: "mallet",
    tags: ["steelpan", "caribbean", "calypso", "world", "modal"],
    desc: "Caribbean steel pan, bright and singing",
    feature: "steel pan modal partials",
    layers: [engine("modal", "steelpan")],
    fx: [verb(0.15, 0.5)],
    knobs: [
      knob("Stick", [0, 1, 0.4], { "modal.hardness": null }, "stick hardness"),
      knob("Ring", [0.1, 10, 1.6], { "modal.ring": null }, "ring time", "exp"),
      knob("Tone", [0, 2, 0.9], { "modal.tilt": null }, "upper partials"),
      knob("Room", [0, 0.6, 0.15], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "singing-bowl",
    category: "mallet",
    tags: ["bowl", "meditation", "tibetan", "drone", "modal"],
    desc: "Tibetan singing bowl with a long, beating ring",
    feature: "modal resonator with very long ring",
    layers: [engine("modal", "bowl")],
    fx: [verb(0.3, 0.8)],
    range: [48, 72],
    knobs: [
      knob(
        "Strike",
        [0, 1, 0.3],
        { "modal.hardness": null },
        "striker hardness",
      ),
      knob("Ring", [1, 30, 8], { "modal.ring": null }, "ring time", "exp"),
      knob("Tone", [0, 2, 0.9], { "modal.tilt": null }, "upper partials"),
      knob("Space", [0, 0.8, 0.3], { "reverb.mix": null }, "reverb"),
    ],
  },
  {
    name: "music-box",
    category: "mallet",
    tags: ["music-box", "toy", "lullaby", "modal"],
    desc: "tinkling music box comb",
    feature: "metal comb modal resonator",
    layers: [engine("modal", "musicbox")],
    fx: [verb(0.25, 0.6)],
    knobs: [
      knob("Pick", [0, 1, 0.6], { "modal.hardness": null }, "pick hardness"),
      knob("Ring", [0.1, 10, 1.6], { "modal.ring": null }, "ring time", "exp"),
      knob("Tone", [0, 2, 0.9], { "modal.tilt": null }, "upper partials"),
      knob("Room", [0, 0.6, 0.25], { "reverb.mix": null }, "room"),
    ],
  },
  {
    name: "gamelan",
    category: "mallet",
    tags: ["gamelan", "indonesian", "ombak", "world", "modal"],
    desc: "Balinese gangsa with paired, beating (ombak) tuning",
    feature: "gamelan pair detuning (ombak beating)",
    guard: true,
    layers: [engine("modal", "gangsa")],
    fx: [verb(0.22, 0.65)],
    knobs: [
      knob(
        "Mallet",
        [0, 1, 0.5],
        { "modal.hardness": null },
        "mallet hardness",
      ),
      knob("Ring", [0.1, 10, 1.6], { "modal.ring": null }, "ring time", "exp"),
      knob("Damp", [0, 1, 0], { "modal.damp": null }, "hand damping"),
      knob("Room", [0, 0.6, 0.22], { "reverb.mix": null }, "room"),
    ],
  },
];
