#!/usr/bin/env bun
/**
 * Measures every built-in preset over the standard phrase and prints a
 * report; `--write` rewrites core/presets/levels.ts so each preset sits at
 * its category's loudness target. `--only a,b` limits the run.
 *
 *   bun scripts/preset-levels.ts            # report
 *   bun scripts/preset-levels.ts --write    # normalise
 *   bun scripts/preset-levels.ts --json --shard 2/8   # one test shard
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { PRESETS } from "../core/presets/index.ts";
import { PRESET_LEVELS } from "../core/presets/levels.ts";
import {
  levelFor,
  measurePreset,
  presetProblems,
} from "../src/audio/preset-check.ts";
import { buildPreset } from "../core/presets/build.ts";
import {
  PRESET_SPECS,
  rebuildModular,
  MODULAR_SOURCES,
} from "../core/presets/index.ts";

const args = process.argv.slice(2);
const write = args.includes("--write");
const onlyAt = args.indexOf("--only");
const only = onlyAt >= 0 ? new Set(args[onlyAt + 1]!.split(",")) : undefined;

const json = args.includes("--json");
const shardAt = args.indexOf("--shard");
const [shard, shards] =
  shardAt >= 0 ? args[shardAt + 1]!.split("/").map(Number) : [1, 1];

const levels: Record<string, number> = { ...PRESET_LEVELS };
const f = (v: number, d = 1) => (Number.isFinite(v) ? v.toFixed(d) : String(v));
let failed = 0;
const rows: unknown[] = [];
const measured = PRESETS.filter((p) => p.patch);
for (const [i, preset] of measured.entries()) {
  if (only && !only.has(preset.name)) continue;
  if (i % shards! !== shard! - 1) continue;
  let m = measurePreset(preset);
  if (write && Number.isFinite(m.lufs)) {
    // Two passes: the second corrects any clip the first gain caused.
    for (let pass = 0; pass < 2; pass += 1) {
      const gain = levelFor(levels[preset.name] ?? 1, m);
      levels[preset.name] = Math.min(16, Math.round(gain * 1000) / 1000);
      const spec = PRESET_SPECS.find((s) => s.name === preset.name);
      const rebuilt = spec
        ? buildPreset(spec, levels)
        : rebuildModular(preset, levels);
      if (!rebuilt) break;
      m = measurePreset(rebuilt);
    }
  }
  const problems = presetProblems(preset, m);
  if (problems.length > 0) failed += 1;
  if (json) {
    rows.push({ name: preset.name, metrics: m, problems });
    continue;
  }
  console.log(
    [
      preset.name.padEnd(18),
      preset.category.padEnd(8),
      `${f(m.lufs)} LUFS`,
      `tp ${f(m.truePeak)}`,
      `corr ${f(m.correlation, 2)}`,
      `vel ${f(m.velocityDb)}`,
      `hi ${f(m.bands.high ?? -99)}`,
      `top ${f(m.topHigh)}`,
      `tail ${f(m.tailDb, 0)}`,
      `cost ${m.cost}`,
      problems.length ? `!! ${problems.join("; ")}` : "ok",
    ].join("  "),
  );
}
if (write) {
  const names = Object.keys(levels)
    .filter(
      (n) =>
        PRESET_SPECS.some((s) => s.name === n) ||
        Object.hasOwn(MODULAR_SOURCES, n),
    )
    .sort();
  const body = names
    .map((n) => `  ${JSON.stringify(n)}: ${levels[n]},`)
    .join("\n");
  writeFileSync(
    join(import.meta.dir, "../core/presets/levels.ts"),
    `/**\n * Level stage gains that put each preset at its category loudness target.\n * Generated by \`bun scripts/preset-levels.ts --write\`; do not edit by hand.\n */\nexport const PRESET_LEVELS: Readonly<Record<string, number>> = Object.freeze({\n${body}\n});\n`,
  );
}
if (json) console.log(JSON.stringify(rows));
else console.log(`${failed} preset(s) with problems`);
